import { resolveConfig } from "better-supabase/config";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { parseArgs } from "../../src/args.ts";
import { runSeed } from "../../src/commands/seed.ts";
import { fakeConnect } from "../fixtures/fake-connect.ts";
import { fakeSql, pgError } from "../fixtures/fake-sql.ts";

const SEED = `export const seed = {
  [Symbol.for("better-supabase.seed")]: true,
  statements: () => ["insert into a values (1);", "insert into b values (2);"],
};
`;

describe("seed", () => {
  let root: string;

  beforeEach(async () => {
    root = await mkdtemp(join(tmpdir(), "better-supabase-seed-"));
  });

  afterEach(async () => {
    await rm(root, { recursive: true, force: true });
  });

  async function write(path: string, contents: string): Promise<void> {
    await mkdir(dirname(join(root, path)), { recursive: true });
    await writeFile(join(root, path), contents);
  }

  const seed = (argv: string[], open?: ReturnType<typeof fakeConnect>) =>
    runSeed(
      resolveConfig({}, root),
      parseArgs(["seed", ...argv]),
      { DATABASE_URL: "postgresql://u:secret@db:5432/app" },
      open?.connect,
    );

  it("rejects a module without a seed", async () => {
    await write("supabase/seed.mjs", "export const seed = 1;\n");
    expect(await seed(["--entry", "supabase/seed.mjs"])).toEqual({
      code: 1,
      error:
        "supabase/seed.mjs must export defineSeed(...) as `seed` or default.",
    });
  });

  it("writes the SQL elsewhere and applies it in one transaction", async () => {
    await write("supabase/seed.mjs", SEED);
    const db = fakeSql();
    const open = fakeConnect(db.pg);
    const result = await seed(
      ["--entry", "supabase/seed.mjs", "--out", "db/seed.sql", "--apply"],
      open,
    );
    expect(result).toEqual({
      code: 0,
      output:
        "Wrote db/seed.sql (2 tables)\nInserted the fixtures (existing rows were kept).",
    });
    expect(open.urls).toEqual(["postgresql://u:secret@db:5432/app"]);
    expect(db.texts()).toEqual([
      "begin",
      "insert into a values (1);",
      "insert into b values (2);",
      "commit",
    ]);
    expect(open.closed()).toBe(1);
    expect(await readFile(join(root, "db/seed.sql"), "utf8")).toBe(
      "-- Generated by `better-supabase seed` from supabase/seed.mjs. Do not edit.\n\ninsert into a values (1);\n\ninsert into b values (2);\n",
    );
  });

  it("rolls back and closes when a statement fails", async () => {
    await write("supabase/seed.mjs", SEED);
    const db = fakeSql([
      ["insert into b", { throws: pgError("23505", "duplicate key") }],
    ]);
    const open = fakeConnect(db.pg);
    await expect(
      seed(["--entry", "supabase/seed.mjs", "--apply"], open),
    ).rejects.toThrow("duplicate key");
    expect(db.texts().at(-1)).toBe("rollback");
    expect(open.closed()).toBe(1);
  });

  it("asks for the seed in config.toml unless a glob already covers it", async () => {
    await write("supabase/seed.mjs", SEED);
    await write(
      "supabase/config.toml",
      '[db.seed]\nsql_paths = ["./seed.sql"]\n',
    );
    const asked = await seed(["--entry", "supabase/seed.mjs"]);
    expect(asked.output).toContain(
      '  sql_paths = ["./seed.sql", "./seeds/000_better_supabase.sql"]',
    );
    await write(
      "supabase/config.toml",
      '[db.seed]\nsql_paths = ["./seeds/*"]\n',
    );
    expect((await seed(["--entry", "supabase/seed.mjs"])).output).toBe(
      "Unchanged supabase/seeds/000_better_supabase.sql (2 tables)",
    );
  });
});
