// Generated by scripts/gen-workflow-ddl.ts from @workflow/world-postgres 5.0.2. Do not edit.

/** The `@workflow/world-postgres` version the DDL below was generated from. */
export const WORLD_POSTGRES_VERSION = "5.0.2";

/** The migrations the DDL reproduces, in journal order. */
export const WORLD_POSTGRES_MIGRATIONS: readonly { readonly tag: string; readonly sha256: string }[] = [
  { tag: "0000_cultured_the_anarchist", sha256: "e92421745b2346049a277afbce781da3f260e68067eb1bdbd7d10bbf2ad2e743" },
  { tag: "0001_tricky_sersi", sha256: "5bb606a2a55a2095101907d62d28917091316d9cddcdff5e8fc9a43e2e6f7a30" },
  { tag: "0002_add_expired_at", sha256: "ac88e448e940f38bf18f076dde2abe63b53659a4c9936325e4e44cf95434e311" },
  { tag: "0003_add_stream_run_id", sha256: "ad911e947a121b1def77b7ad37bd95ae7de2b453a05645e9b40f979a166e79b9" },
  { tag: "0004_remove_run_pause_status", sha256: "673b7222d0df6c2fd2d335072a9d85b695b5dae4a2c52b287d2aaa5d31d462f9" },
  { tag: "0005_add_spec_version", sha256: "7c3f3b73a707af2386f5c20b953e4c54631be616bf0b9bfa8ced1b97018ad384" },
  { tag: "0006_add_error_cbor", sha256: "928760bfbdd23576f119f3f14c3e6db78fb765cfd24f8595c70536cb975c7178" },
  { tag: "0007_add_waits_table", sha256: "f904ecb9232a269f599b393fa4ce5e3762a8267d111ad103d56fdcd11837fdcd" },
  { tag: "0008_migrate_pgboss_to_graphile", sha256: "e424a48df5a1ddd752e4d09f05696e76da94e366b3d617ca10c3d3fbcdb74c77" },
  { tag: "0009_add_is_webhook", sha256: "eafc36b3c9b1aaff44cd33cff9126bd7fdd796d2672b104125c32d91e0ce5597" },
  { tag: "0010_add_events_entity_creation_unique_index", sha256: "5584c9be57e2c0d82fa1e972d5ee5da711b31368fbf8efee16cd2857e071af41" },
  { tag: "0011_add_error_code", sha256: "169d2d8dea24763593830768249a1832b951a8a456f3757a2a2aa08063b41f6b" },
  { tag: "0012_add_is_system", sha256: "31308216105f22820ff834667fd3c34cc53939deeff5f56d9865f77a5579105d" },
  { tag: "0013_add_attributes", sha256: "f22c7907d5cbfcf8e85801490677aae0fa9212fca01ad5a27aec0f8742cb2be7" },
  { tag: "0014_add_attr_set_event_unique_index", sha256: "f09414bc7166d782e8c93f6d65e3b16493b56911b1a241356b382f7e6008439f" },
  { tag: "0015_move_enums_to_workflow_schema", sha256: "adc88e08a9a0bba0bd13962db0c317b4e4aab4c6ae6ec281f2453dee9e4199c7" },
  { tag: "0016_add_encryption_public_key", sha256: "f54db91ba1d89a06bfa1dcd6f869dfe419b94fc54b0329052e2a18e314ee5a82" },
  { tag: "0017_add_hook_resume_context", sha256: "4ce073262fcb6bb23919f5c57df2bd513b95bff75d104a0c9131840eca6e4846" },
  { tag: "0018_add_hook_token_retention", sha256: "28feaa8700bbe8ca2402e9b50db2b966e70b9be954eb1c75579a67adba1a7d98" },
  { tag: "0019_add_event_slots", sha256: "81e4aa926131374e338b11c2a2b6105266617f5b7f75b02cf966afd834dbc0bf" },
  { tag: "0020_add_invocations", sha256: "1f1f72fbb5062f4daf8b9876b72f0e5535b1db2726e480b1f4dfb2304500bf00" },
  { tag: "0021_invocation_identity_retention", sha256: "02a86bea8cda78bfda21f197d90273c30a55efa5d587c63a62843f20d2c3adb4" },
  { tag: "0022_invocation_outcomes", sha256: "ce83e2d48c02b4897faeadd310c52bf326d7d9a11f6a266a30ea779334259c06" },
  { tag: "0023_add_hook_claimed_from", sha256: "cc8ef02fd74872bee4a09ff2ce29a9c85058c8f217224fbfec107a2663a775d7" },
  { tag: "0024_add_dynamic_workflow_code", sha256: "0c60b6f7d20a1629bfe0a6c5c2b503d5c925d783bfff30470686828a0afb6ca4" },
  { tag: "0025_add_snapshots_table", sha256: "778c6d87381429bc4da17f91001c2f819cce103c0a942accda6bcf4fce626f99" },
];

/** The `workflow` schema after every migration above, as idempotent DDL. */
export const WORLD_POSTGRES_DDL = `create schema if not exists workflow;

do $$ begin
  create type workflow.status as enum ('pending', 'running', 'completed', 'failed', 'cancelled');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type workflow.step_status as enum ('pending', 'running', 'completed', 'failed', 'cancelled');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type workflow.wait_status as enum ('waiting', 'completed');
exception when duplicate_object then null;
end $$;

create table if not exists workflow.workflow_event_slots (
  "run_id" character varying not null,
  constraint "workflow_event_slots_pkey" PRIMARY KEY (run_id)
);

alter table workflow.workflow_event_slots
  add column if not exists "run_id" character varying not null;

create table if not exists workflow.workflow_events (
  "id" character varying not null,
  "type" character varying not null,
  "correlation_id" character varying,
  "created_at" timestamp without time zone not null default now(),
  "run_id" character varying not null,
  "payload" jsonb,
  "payload_cbor" bytea,
  "spec_version" integer,
  "resume_id" character varying,
  "resume_payload_digest" character varying,
  constraint "workflow_events_run_id_id_pk" PRIMARY KEY (run_id, id)
);

alter table workflow.workflow_events
  add column if not exists "id" character varying not null,
  add column if not exists "type" character varying not null,
  add column if not exists "correlation_id" character varying,
  add column if not exists "created_at" timestamp without time zone not null default now(),
  add column if not exists "run_id" character varying not null,
  add column if not exists "payload" jsonb,
  add column if not exists "payload_cbor" bytea,
  add column if not exists "spec_version" integer,
  add column if not exists "resume_id" character varying,
  add column if not exists "resume_payload_digest" character varying;

create index if not exists workflow_events_correlation_id_index ON workflow.workflow_events USING btree (correlation_id);

create unique index if not exists workflow_events_entity_creation_unique ON workflow.workflow_events USING btree (run_id, correlation_id, type) WHERE ((type)::text = ANY ((ARRAY['step_created'::character varying, 'hook_created'::character varying, 'wait_created'::character varying, 'attr_set'::character varying])::text[]));

create unique index if not exists workflow_events_hook_resume_unique ON workflow.workflow_events USING btree (run_id, resume_id) WHERE (((type)::text = 'hook_received'::text) AND (resume_id IS NOT NULL));

create table if not exists workflow.workflow_hooks (
  "run_id" character varying not null,
  "hook_id" character varying not null,
  "token" character varying not null,
  "owner_id" character varying not null,
  "project_id" character varying not null,
  "environment" character varying not null,
  "created_at" timestamp without time zone not null default now(),
  "metadata" jsonb,
  "metadata_cbor" bytea,
  "spec_version" integer,
  "is_webhook" boolean default true,
  "is_system" boolean default false,
  "resume_context" bytea,
  "token_retention_until" timestamp with time zone,
  "claimed_from" bytea,
  constraint "workflow_hooks_pkey" PRIMARY KEY (hook_id)
);

alter table workflow.workflow_hooks
  add column if not exists "run_id" character varying not null,
  add column if not exists "hook_id" character varying not null,
  add column if not exists "token" character varying not null,
  add column if not exists "owner_id" character varying not null,
  add column if not exists "project_id" character varying not null,
  add column if not exists "environment" character varying not null,
  add column if not exists "created_at" timestamp without time zone not null default now(),
  add column if not exists "metadata" jsonb,
  add column if not exists "metadata_cbor" bytea,
  add column if not exists "spec_version" integer,
  add column if not exists "is_webhook" boolean default true,
  add column if not exists "is_system" boolean default false,
  add column if not exists "resume_context" bytea,
  add column if not exists "token_retention_until" timestamp with time zone,
  add column if not exists "claimed_from" bytea;

create index if not exists workflow_hooks_run_id_index ON workflow.workflow_hooks USING btree (run_id);

create index if not exists workflow_hooks_token_index ON workflow.workflow_hooks USING btree (token);

create table if not exists workflow.workflow_invocations (
  "sequence" bigserial,
  "run_id" character varying not null,
  "request_id" character varying not null,
  "payload" bytea,
  "fingerprint" character varying,
  "result" bytea,
  "created_at" timestamp without time zone not null default now(),
  "responded_at" timestamp without time zone,
  "expired_at" timestamp without time zone,
  "result_version" integer not null default 0,
  constraint "workflow_invocations_pkey" PRIMARY KEY (run_id, request_id)
);

alter table workflow.workflow_invocations
  add column if not exists "sequence" bigserial,
  add column if not exists "run_id" character varying not null,
  add column if not exists "request_id" character varying not null,
  add column if not exists "payload" bytea,
  add column if not exists "fingerprint" character varying,
  add column if not exists "result" bytea,
  add column if not exists "created_at" timestamp without time zone not null default now(),
  add column if not exists "responded_at" timestamp without time zone,
  add column if not exists "expired_at" timestamp without time zone,
  add column if not exists "result_version" integer not null default 0;

create index if not exists workflow_invocations_pending ON workflow.workflow_invocations USING btree (run_id, sequence) WHERE (responded_at IS NULL);

create table if not exists workflow.workflow_runs (
  "id" character varying not null,
  "output" jsonb,
  "deployment_id" character varying not null,
  "status" workflow.status not null,
  "name" character varying not null,
  "execution_context" jsonb,
  "input" jsonb,
  "error" text,
  "created_at" timestamp without time zone not null default now(),
  "updated_at" timestamp without time zone not null default now(),
  "completed_at" timestamp without time zone,
  "started_at" timestamp without time zone,
  "output_cbor" bytea,
  "execution_context_cbor" bytea,
  "input_cbor" bytea,
  "expired_at" timestamp without time zone,
  "spec_version" character varying,
  "error_cbor" bytea,
  "error_code" character varying,
  "attributes" jsonb not null default '{}'::jsonb,
  "encryption_public_key" character varying,
  "dynamic_workflow_code_cbor" bytea,
  constraint "workflow_runs_pkey" PRIMARY KEY (id)
);

alter table workflow.workflow_runs
  add column if not exists "id" character varying not null,
  add column if not exists "output" jsonb,
  add column if not exists "deployment_id" character varying not null,
  add column if not exists "status" workflow.status not null,
  add column if not exists "name" character varying not null,
  add column if not exists "execution_context" jsonb,
  add column if not exists "input" jsonb,
  add column if not exists "error" text,
  add column if not exists "created_at" timestamp without time zone not null default now(),
  add column if not exists "updated_at" timestamp without time zone not null default now(),
  add column if not exists "completed_at" timestamp without time zone,
  add column if not exists "started_at" timestamp without time zone,
  add column if not exists "output_cbor" bytea,
  add column if not exists "execution_context_cbor" bytea,
  add column if not exists "input_cbor" bytea,
  add column if not exists "expired_at" timestamp without time zone,
  add column if not exists "spec_version" character varying,
  add column if not exists "error_cbor" bytea,
  add column if not exists "error_code" character varying,
  add column if not exists "attributes" jsonb not null default '{}'::jsonb,
  add column if not exists "encryption_public_key" character varying,
  add column if not exists "dynamic_workflow_code_cbor" bytea;

create index if not exists workflow_runs_name_index ON workflow.workflow_runs USING btree (name);

create index if not exists workflow_runs_status_index ON workflow.workflow_runs USING btree (status);

create table if not exists workflow.workflow_snapshots (
  "run_id" character varying not null,
  "data" bytea not null,
  "events_cursor" character varying,
  "created_at" timestamp without time zone not null default now(),
  constraint "workflow_snapshots_pkey" PRIMARY KEY (run_id)
);

alter table workflow.workflow_snapshots
  add column if not exists "run_id" character varying not null,
  add column if not exists "data" bytea not null,
  add column if not exists "events_cursor" character varying,
  add column if not exists "created_at" timestamp without time zone not null default now();

create table if not exists workflow.workflow_steps (
  "run_id" character varying not null,
  "step_id" character varying not null,
  "step_name" character varying not null,
  "status" workflow.step_status not null,
  "input" jsonb,
  "output" jsonb,
  "error" text,
  "attempt" integer not null,
  "started_at" timestamp without time zone,
  "completed_at" timestamp without time zone,
  "created_at" timestamp without time zone not null default now(),
  "updated_at" timestamp without time zone not null default now(),
  "retry_after" timestamp without time zone,
  "input_cbor" bytea,
  "output_cbor" bytea,
  "error_cbor" bytea,
  "spec_version" integer,
  constraint "workflow_steps_pkey" PRIMARY KEY (step_id)
);

alter table workflow.workflow_steps
  add column if not exists "run_id" character varying not null,
  add column if not exists "step_id" character varying not null,
  add column if not exists "step_name" character varying not null,
  add column if not exists "status" workflow.step_status not null,
  add column if not exists "input" jsonb,
  add column if not exists "output" jsonb,
  add column if not exists "error" text,
  add column if not exists "attempt" integer not null,
  add column if not exists "started_at" timestamp without time zone,
  add column if not exists "completed_at" timestamp without time zone,
  add column if not exists "created_at" timestamp without time zone not null default now(),
  add column if not exists "updated_at" timestamp without time zone not null default now(),
  add column if not exists "retry_after" timestamp without time zone,
  add column if not exists "input_cbor" bytea,
  add column if not exists "output_cbor" bytea,
  add column if not exists "error_cbor" bytea,
  add column if not exists "spec_version" integer;

create index if not exists workflow_steps_run_id_index ON workflow.workflow_steps USING btree (run_id);

create index if not exists workflow_steps_status_index ON workflow.workflow_steps USING btree (status);

create table if not exists workflow.workflow_stream_chunks (
  "id" character varying not null,
  "stream_id" character varying not null,
  "data" bytea not null,
  "created_at" timestamp without time zone not null default now(),
  "eof" boolean not null,
  "run_id" character varying,
  constraint "workflow_stream_chunks_stream_id_id_pk" PRIMARY KEY (stream_id, id)
);

alter table workflow.workflow_stream_chunks
  add column if not exists "id" character varying not null,
  add column if not exists "stream_id" character varying not null,
  add column if not exists "data" bytea not null,
  add column if not exists "created_at" timestamp without time zone not null default now(),
  add column if not exists "eof" boolean not null,
  add column if not exists "run_id" character varying;

create index if not exists workflow_stream_chunks_run_id_index ON workflow.workflow_stream_chunks USING btree (run_id);

create table if not exists workflow.workflow_waits (
  "wait_id" character varying not null,
  "run_id" character varying not null,
  "status" workflow.wait_status not null,
  "resume_at" timestamp without time zone,
  "completed_at" timestamp without time zone,
  "created_at" timestamp without time zone not null default now(),
  "updated_at" timestamp without time zone not null default now(),
  "spec_version" integer,
  constraint "workflow_waits_pkey" PRIMARY KEY (wait_id)
);

alter table workflow.workflow_waits
  add column if not exists "wait_id" character varying not null,
  add column if not exists "run_id" character varying not null,
  add column if not exists "status" workflow.wait_status not null,
  add column if not exists "resume_at" timestamp without time zone,
  add column if not exists "completed_at" timestamp without time zone,
  add column if not exists "created_at" timestamp without time zone not null default now(),
  add column if not exists "updated_at" timestamp without time zone not null default now(),
  add column if not exists "spec_version" integer;

create index if not exists workflow_waits_run_id_index ON workflow.workflow_waits USING btree (run_id);
`;
