// Generated by better-supabase. Do not edit; run `better-supabase gen`.

import { z } from "zod";

import type { InsertOf, RowOf, UpdateOf } from "./generated-camel.ts";

export const contactsRow: z.ZodType<RowOf<'contacts'>> = z.object({
  id: z.guid(),
  organizationId: z.guid(),
  email: z.string(),
  fullName: z.string().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
});
export const contactsInsert: z.ZodType<InsertOf<'contacts'>> = z.object({
  id: z.guid().exactOptional(),
  organizationId: z.guid(),
  email: z.string(),
  fullName: z.string().nullable().exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
});
export const contactsUpdate: z.ZodType<UpdateOf<'contacts'>> = z.object({
  id: z.guid().exactOptional(),
  organizationId: z.guid().exactOptional(),
  email: z.string().exactOptional(),
  fullName: z.string().nullable().exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
});

export const customersRow: z.ZodType<RowOf<'customers'>> = z.object({
  id: z.guid(),
  organizationId: z.guid(),
  name: z.string(),
  kvk: z.string().nullable(),
  status: z.enum(["lead", "active", "archived"]),
  primaryContactId: z.guid().nullable(),
  metadata: z.custom<NonNullable<RowOf<'customers'>['metadata']>>((value) => value !== undefined),
  createdBy: z.guid().nullable(),
  updatedBy: z.guid().nullable(),
  archivedAt: z.iso.datetime({ offset: true }).nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
  logoPath: (z.string() as unknown as z.ZodType<NonNullable<RowOf<'customers'>['logoPath']>>).nullable(),
});
export const customersInsert: z.ZodType<InsertOf<'customers'>> = z.object({
  id: z.guid().exactOptional(),
  organizationId: z.guid(),
  name: z.string(),
  kvk: z.string().nullable().exactOptional(),
  status: z.enum(["lead", "active", "archived"]).exactOptional(),
  primaryContactId: z.guid().nullable().exactOptional(),
  metadata: z.custom<NonNullable<RowOf<'customers'>['metadata']>>((value) => value !== undefined).exactOptional(),
  createdBy: z.guid().nullable().exactOptional(),
  updatedBy: z.guid().nullable().exactOptional(),
  archivedAt: z.iso.datetime({ offset: true }).nullable().exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
  logoPath: (z.string() as unknown as z.ZodType<NonNullable<RowOf<'customers'>['logoPath']>>).nullable().exactOptional(),
});
export const customersUpdate: z.ZodType<UpdateOf<'customers'>> = z.object({
  id: z.guid().exactOptional(),
  organizationId: z.guid().exactOptional(),
  name: z.string().exactOptional(),
  kvk: z.string().nullable().exactOptional(),
  status: z.enum(["lead", "active", "archived"]).exactOptional(),
  primaryContactId: z.guid().nullable().exactOptional(),
  metadata: z.custom<NonNullable<RowOf<'customers'>['metadata']>>((value) => value !== undefined).exactOptional(),
  createdBy: z.guid().nullable().exactOptional(),
  updatedBy: z.guid().nullable().exactOptional(),
  archivedAt: z.iso.datetime({ offset: true }).nullable().exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
  logoPath: (z.string() as unknown as z.ZodType<NonNullable<RowOf<'customers'>['logoPath']>>).nullable().exactOptional(),
});

export const customerTagsRow: z.ZodType<RowOf<'customerTags'>> = z.object({
  customerId: z.guid(),
  tagId: z.guid(),
  organizationId: z.guid(),
});
export const customerTagsInsert: z.ZodType<InsertOf<'customerTags'>> = z.object({
  customerId: z.guid(),
  tagId: z.guid(),
  organizationId: z.guid(),
});
export const customerTagsUpdate: z.ZodType<UpdateOf<'customerTags'>> = z.object({
  customerId: z.guid().exactOptional(),
  tagId: z.guid().exactOptional(),
  organizationId: z.guid().exactOptional(),
});

export const locationsRow: z.ZodType<RowOf<'locations'>> = z.object({
  id: z.guid(),
  organizationId: z.guid(),
  customerId: z.guid(),
  label: z.string(),
  city: z.string().nullable(),
  isPrimary: z.boolean(),
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
});
export const locationsInsert: z.ZodType<InsertOf<'locations'>> = z.object({
  id: z.guid().exactOptional(),
  organizationId: z.guid(),
  customerId: z.guid(),
  label: z.string(),
  city: z.string().nullable().exactOptional(),
  isPrimary: z.boolean().exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
});
export const locationsUpdate: z.ZodType<UpdateOf<'locations'>> = z.object({
  id: z.guid().exactOptional(),
  organizationId: z.guid().exactOptional(),
  customerId: z.guid().exactOptional(),
  label: z.string().exactOptional(),
  city: z.string().nullable().exactOptional(),
  isPrimary: z.boolean().exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
});

export const notesRow: z.ZodType<RowOf<'notes'>> = z.object({
  id: z.int(),
  organizationId: z.guid(),
  customerId: z.guid(),
  kind: z.enum(["call", "meeting", "email"]),
  body: z.string(),
  attachments: z.json().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
});
export const notesInsert: z.ZodType<InsertOf<'notes'>> = z.object({
  organizationId: z.guid(),
  customerId: z.guid(),
  kind: z.enum(["call", "meeting", "email"]).exactOptional(),
  body: z.string(),
  attachments: z.json().nullable().exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
});
export const notesUpdate: z.ZodType<UpdateOf<'notes'>> = z.object({
  organizationId: z.guid().exactOptional(),
  customerId: z.guid().exactOptional(),
  kind: z.enum(["call", "meeting", "email"]).exactOptional(),
  body: z.string().exactOptional(),
  attachments: z.json().nullable().exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
});

export const organizationsRow: z.ZodType<RowOf<'organizations'>> = z.object({
  id: z.guid(),
  name: z.string(),
  slug: z.string(),
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
});
export const organizationsInsert: z.ZodType<InsertOf<'organizations'>> = z.object({
  id: z.guid().exactOptional(),
  name: z.string(),
  slug: z.string(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
});
export const organizationsUpdate: z.ZodType<UpdateOf<'organizations'>> = z.object({
  id: z.guid().exactOptional(),
  name: z.string().exactOptional(),
  slug: z.string().exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
});

export const tagsRow: z.ZodType<RowOf<'tags'>> = z.object({
  id: z.guid(),
  organizationId: z.guid(),
  name: z.string(),
  color: z.enum(["gray", "red", "green", "blue"]),
});
export const tagsInsert: z.ZodType<InsertOf<'tags'>> = z.object({
  id: z.guid().exactOptional(),
  organizationId: z.guid(),
  name: z.string(),
  color: z.enum(["gray", "red", "green", "blue"]).exactOptional(),
});
export const tagsUpdate: z.ZodType<UpdateOf<'tags'>> = z.object({
  id: z.guid().exactOptional(),
  organizationId: z.guid().exactOptional(),
  name: z.string().exactOptional(),
  color: z.enum(["gray", "red", "green", "blue"]).exactOptional(),
});

/** Write validators for the validation plugin. */
export const validators: {
  readonly contacts: { readonly insert: typeof contactsInsert; readonly update: typeof contactsUpdate };
  readonly customers: { readonly insert: typeof customersInsert; readonly update: typeof customersUpdate };
  readonly customerTags: { readonly insert: typeof customerTagsInsert; readonly update: typeof customerTagsUpdate };
  readonly locations: { readonly insert: typeof locationsInsert; readonly update: typeof locationsUpdate };
  readonly notes: { readonly insert: typeof notesInsert; readonly update: typeof notesUpdate };
  readonly organizations: { readonly insert: typeof organizationsInsert; readonly update: typeof organizationsUpdate };
  readonly tags: { readonly insert: typeof tagsInsert; readonly update: typeof tagsUpdate };
} = {
  contacts: { insert: contactsInsert, update: contactsUpdate },
  customers: { insert: customersInsert, update: customersUpdate },
  customerTags: { insert: customerTagsInsert, update: customerTagsUpdate },
  locations: { insert: locationsInsert, update: locationsUpdate },
  notes: { insert: notesInsert, update: notesUpdate },
  organizations: { insert: organizationsInsert, update: organizationsUpdate },
  tags: { insert: tagsInsert, update: tagsUpdate },
};
