// Generated by better-supabase. Do not edit; run `better-supabase gen`.

import * as v from "valibot";

import type { InsertOf, Json, RowOf, UpdateOf } from "./generated-camel.ts";

const json: v.GenericSchema<Json> = v.lazy(() =>
  v.union([v.string(), v.number(), v.boolean(), v.null(), v.array(json), v.record(v.string(), v.optional(json))]),
);

export const contactsRow: v.GenericSchema<RowOf<'contacts'>> = v.object({
  id: v.pipe(v.string(), v.uuid()),
  organizationId: v.pipe(v.string(), v.uuid()),
  email: v.string(),
  fullName: v.nullable(v.string()),
  createdAt: v.pipe(v.string(), v.isoTimestamp()),
  updatedAt: v.pipe(v.string(), v.isoTimestamp()),
});
export const contactsInsert: v.GenericSchema<InsertOf<'contacts'>> = v.object({
  id: v.exactOptional(v.pipe(v.string(), v.uuid())),
  organizationId: v.pipe(v.string(), v.uuid()),
  email: v.string(),
  fullName: v.exactOptional(v.nullable(v.string())),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
});
export const contactsUpdate: v.GenericSchema<UpdateOf<'contacts'>> = v.object({
  id: v.exactOptional(v.pipe(v.string(), v.uuid())),
  organizationId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  email: v.exactOptional(v.string()),
  fullName: v.exactOptional(v.nullable(v.string())),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
});

export const customersRow: v.GenericSchema<RowOf<'customers'>> = v.object({
  id: v.pipe(v.string(), v.uuid()),
  organizationId: v.pipe(v.string(), v.uuid()),
  name: v.string(),
  kvk: v.nullable(v.string()),
  status: v.picklist(["lead", "active", "archived"]),
  primaryContactId: v.nullable(v.pipe(v.string(), v.uuid())),
  metadata: v.custom<NonNullable<RowOf<'customers'>['metadata']>>((value) => value !== undefined),
  createdBy: v.nullable(v.pipe(v.string(), v.uuid())),
  updatedBy: v.nullable(v.pipe(v.string(), v.uuid())),
  archivedAt: v.nullable(v.pipe(v.string(), v.isoTimestamp())),
  createdAt: v.pipe(v.string(), v.isoTimestamp()),
  updatedAt: v.pipe(v.string(), v.isoTimestamp()),
  logoPath: v.nullable((v.string() as unknown as v.GenericSchema<NonNullable<RowOf<'customers'>['logoPath']>>)),
});
export const customersInsert: v.GenericSchema<InsertOf<'customers'>> = v.object({
  id: v.exactOptional(v.pipe(v.string(), v.uuid())),
  organizationId: v.pipe(v.string(), v.uuid()),
  name: v.string(),
  kvk: v.exactOptional(v.nullable(v.string())),
  status: v.exactOptional(v.picklist(["lead", "active", "archived"])),
  primaryContactId: v.exactOptional(v.nullable(v.pipe(v.string(), v.uuid()))),
  metadata: v.exactOptional(v.custom<NonNullable<RowOf<'customers'>['metadata']>>((value) => value !== undefined)),
  createdBy: v.exactOptional(v.nullable(v.pipe(v.string(), v.uuid()))),
  updatedBy: v.exactOptional(v.nullable(v.pipe(v.string(), v.uuid()))),
  archivedAt: v.exactOptional(v.nullable(v.pipe(v.string(), v.isoTimestamp()))),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  logoPath: v.exactOptional(v.nullable((v.string() as unknown as v.GenericSchema<NonNullable<RowOf<'customers'>['logoPath']>>))),
});
export const customersUpdate: v.GenericSchema<UpdateOf<'customers'>> = v.object({
  id: v.exactOptional(v.pipe(v.string(), v.uuid())),
  organizationId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  name: v.exactOptional(v.string()),
  kvk: v.exactOptional(v.nullable(v.string())),
  status: v.exactOptional(v.picklist(["lead", "active", "archived"])),
  primaryContactId: v.exactOptional(v.nullable(v.pipe(v.string(), v.uuid()))),
  metadata: v.exactOptional(v.custom<NonNullable<RowOf<'customers'>['metadata']>>((value) => value !== undefined)),
  createdBy: v.exactOptional(v.nullable(v.pipe(v.string(), v.uuid()))),
  updatedBy: v.exactOptional(v.nullable(v.pipe(v.string(), v.uuid()))),
  archivedAt: v.exactOptional(v.nullable(v.pipe(v.string(), v.isoTimestamp()))),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  logoPath: v.exactOptional(v.nullable((v.string() as unknown as v.GenericSchema<NonNullable<RowOf<'customers'>['logoPath']>>))),
});

export const customerTagsRow: v.GenericSchema<RowOf<'customerTags'>> = v.object({
  customerId: v.pipe(v.string(), v.uuid()),
  tagId: v.pipe(v.string(), v.uuid()),
  organizationId: v.pipe(v.string(), v.uuid()),
});
export const customerTagsInsert: v.GenericSchema<InsertOf<'customerTags'>> = v.object({
  customerId: v.pipe(v.string(), v.uuid()),
  tagId: v.pipe(v.string(), v.uuid()),
  organizationId: v.pipe(v.string(), v.uuid()),
});
export const customerTagsUpdate: v.GenericSchema<UpdateOf<'customerTags'>> = v.object({
  customerId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  tagId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  organizationId: v.exactOptional(v.pipe(v.string(), v.uuid())),
});

export const locationsRow: v.GenericSchema<RowOf<'locations'>> = v.object({
  id: v.pipe(v.string(), v.uuid()),
  organizationId: v.pipe(v.string(), v.uuid()),
  customerId: v.pipe(v.string(), v.uuid()),
  label: v.string(),
  city: v.nullable(v.string()),
  isPrimary: v.boolean(),
  createdAt: v.pipe(v.string(), v.isoTimestamp()),
  updatedAt: v.pipe(v.string(), v.isoTimestamp()),
});
export const locationsInsert: v.GenericSchema<InsertOf<'locations'>> = v.object({
  id: v.exactOptional(v.pipe(v.string(), v.uuid())),
  organizationId: v.pipe(v.string(), v.uuid()),
  customerId: v.pipe(v.string(), v.uuid()),
  label: v.string(),
  city: v.exactOptional(v.nullable(v.string())),
  isPrimary: v.exactOptional(v.boolean()),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
});
export const locationsUpdate: v.GenericSchema<UpdateOf<'locations'>> = v.object({
  id: v.exactOptional(v.pipe(v.string(), v.uuid())),
  organizationId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  customerId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  label: v.exactOptional(v.string()),
  city: v.exactOptional(v.nullable(v.string())),
  isPrimary: v.exactOptional(v.boolean()),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
});

export const notesRow: v.GenericSchema<RowOf<'notes'>> = v.object({
  id: v.pipe(v.number(), v.integer()),
  organizationId: v.pipe(v.string(), v.uuid()),
  customerId: v.pipe(v.string(), v.uuid()),
  kind: v.picklist(["call", "meeting", "email"]),
  body: v.string(),
  attachments: v.nullable(json),
  createdAt: v.pipe(v.string(), v.isoTimestamp()),
  updatedAt: v.pipe(v.string(), v.isoTimestamp()),
});
export const notesInsert: v.GenericSchema<InsertOf<'notes'>> = v.object({
  organizationId: v.pipe(v.string(), v.uuid()),
  customerId: v.pipe(v.string(), v.uuid()),
  kind: v.exactOptional(v.picklist(["call", "meeting", "email"])),
  body: v.string(),
  attachments: v.exactOptional(v.nullable(json)),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
});
export const notesUpdate: v.GenericSchema<UpdateOf<'notes'>> = v.object({
  organizationId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  customerId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  kind: v.exactOptional(v.picklist(["call", "meeting", "email"])),
  body: v.exactOptional(v.string()),
  attachments: v.exactOptional(v.nullable(json)),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
});

export const organizationsRow: v.GenericSchema<RowOf<'organizations'>> = v.object({
  id: v.pipe(v.string(), v.uuid()),
  name: v.string(),
  slug: v.string(),
  createdAt: v.pipe(v.string(), v.isoTimestamp()),
  updatedAt: v.pipe(v.string(), v.isoTimestamp()),
});
export const organizationsInsert: v.GenericSchema<InsertOf<'organizations'>> = v.object({
  id: v.exactOptional(v.pipe(v.string(), v.uuid())),
  name: v.string(),
  slug: v.string(),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
});
export const organizationsUpdate: v.GenericSchema<UpdateOf<'organizations'>> = v.object({
  id: v.exactOptional(v.pipe(v.string(), v.uuid())),
  name: v.exactOptional(v.string()),
  slug: v.exactOptional(v.string()),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
});

export const tagsRow: v.GenericSchema<RowOf<'tags'>> = v.object({
  id: v.pipe(v.string(), v.uuid()),
  organizationId: v.pipe(v.string(), v.uuid()),
  name: v.string(),
  color: v.picklist(["gray", "red", "green", "blue"]),
});
export const tagsInsert: v.GenericSchema<InsertOf<'tags'>> = v.object({
  id: v.exactOptional(v.pipe(v.string(), v.uuid())),
  organizationId: v.pipe(v.string(), v.uuid()),
  name: v.string(),
  color: v.exactOptional(v.picklist(["gray", "red", "green", "blue"])),
});
export const tagsUpdate: v.GenericSchema<UpdateOf<'tags'>> = v.object({
  id: v.exactOptional(v.pipe(v.string(), v.uuid())),
  organizationId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  name: v.exactOptional(v.string()),
  color: v.exactOptional(v.picklist(["gray", "red", "green", "blue"])),
});

/** Write validators for the validation plugin. */
export const validators: {
  readonly contacts: { readonly insert: typeof contactsInsert; readonly update: typeof contactsUpdate };
  readonly customers: { readonly insert: typeof customersInsert; readonly update: typeof customersUpdate };
  readonly customerTags: { readonly insert: typeof customerTagsInsert; readonly update: typeof customerTagsUpdate };
  readonly locations: { readonly insert: typeof locationsInsert; readonly update: typeof locationsUpdate };
  readonly notes: { readonly insert: typeof notesInsert; readonly update: typeof notesUpdate };
  readonly organizations: { readonly insert: typeof organizationsInsert; readonly update: typeof organizationsUpdate };
  readonly tags: { readonly insert: typeof tagsInsert; readonly update: typeof tagsUpdate };
} = {
  contacts: { insert: contactsInsert, update: contactsUpdate },
  customers: { insert: customersInsert, update: customersUpdate },
  customerTags: { insert: customerTagsInsert, update: customerTagsUpdate },
  locations: { insert: locationsInsert, update: locationsUpdate },
  notes: { insert: notesInsert, update: notesUpdate },
  organizations: { insert: organizationsInsert, update: organizationsUpdate },
  tags: { insert: tagsInsert, update: tagsUpdate },
};
