// @generated by better-supabase gen. Do not edit; run `better-supabase gen` instead.
/* oxlint-disable */
/* eslint-disable */

import { defineSchema, type Schema } from "better-supabase";
import type { EnrichDatabase, MutableWhere, OrderByArg, OrderByInput } from "better-supabase";
import type { Database as SupabaseDatabase } from "./database.types.ts";
import meta from "./generated.meta.js";

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = EnrichDatabase<
  SupabaseDatabase,
  {
    public: {
      customers: {
        status: "lead" | "active" | "archived";
      };
      memberships: {
        role: "owner" | "admin" | "member";
      };
      subscriptions: {
        status: "active" | "trialing" | "past_due" | "canceled";
      };
      tags: {
        color: "gray" | "red" | "green" | "blue";
      };
    };
  }
>;

export const noteKindValues = ["call", "meeting", "email"] as const;
export type NoteKind = (typeof noteKindValues)[number];
export const customersStatusValues = ["lead", "active", "archived"] as const;
export type CustomersStatus = (typeof customersStatusValues)[number];
export const membershipsRoleValues = ["owner", "admin", "member"] as const;
export type MembershipsRole = (typeof membershipsRoleValues)[number];
export const subscriptionsStatusValues = ["active", "trialing", "past_due", "canceled"] as const;
export type SubscriptionsStatus = (typeof subscriptionsStatusValues)[number];
export const tagsColorValues = ["gray", "red", "green", "blue"] as const;
export type TagsColor = (typeof tagsColorValues)[number];

export type Models = {
  contacts: {
    Row: {
      id: string;
      organization_id: string;
      email: string;
      full_name: string | null;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      organization_id: string;
      email: string;
      full_name?: string | null;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      organization_id?: string;
      email?: string;
      full_name?: string | null;
      created_at?: string;
      updated_at?: string;
    };
    Relations: {
      organization: { table: "organizations"; kind: "one"; nullable: false };
      customers: { table: "customers"; kind: "many"; nullable: true };
    };
    PrimaryKey: "id";
    UniqueKeys: {
      contacts_id_organization_id_key: readonly ["id", "organization_id"];
    };
    Checks: never;
    ForeignKeys: "contacts_organization_id_fkey";
    Flags: Record<never, never>;
  };
  customer_tags: {
    Row: {
      customer_id: string;
      tag_id: string;
      organization_id: string;
      created_at: string;
    };
    Insert: {
      customer_id: string;
      tag_id: string;
      organization_id: string;
      created_at?: string;
    };
    Update: {
      customer_id?: string;
      tag_id?: string;
      organization_id?: string;
      created_at?: string;
    };
    Relations: {
      customer: { table: "customers"; kind: "one"; nullable: false };
      organization: { table: "organizations"; kind: "one"; nullable: false };
      tag: { table: "tags"; kind: "one"; nullable: false };
    };
    PrimaryKey: "customer_id" | "tag_id";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "customer_tags_customer_id_fkey" | "customer_tags_organization_id_fkey" | "customer_tags_tag_id_fkey";
    Flags: Record<never, never>;
  };
  customers: {
    Row: {
      id: string;
      organization_id: string;
      name: string;
      kvk: string | null;
      status: "lead" | "active" | "archived";
      primary_contact_id: string | null;
      metadata: Json;
      created_by: string | null;
      updated_by: string | null;
      archived_at: string | null;
      created_at: string;
      updated_at: string;
      logo_path: string | null;
    };
    Insert: {
      id?: string;
      organization_id: string;
      name: string;
      kvk?: string | null;
      status?: "lead" | "active" | "archived";
      primary_contact_id?: string | null;
      metadata?: Json;
      created_by?: string | null;
      updated_by?: string | null;
      archived_at?: string | null;
      created_at?: string;
      updated_at?: string;
      logo_path?: string | null;
    };
    Update: {
      id?: string;
      organization_id?: string;
      name?: string;
      kvk?: string | null;
      status?: "lead" | "active" | "archived";
      primary_contact_id?: string | null;
      metadata?: Json;
      created_by?: string | null;
      updated_by?: string | null;
      archived_at?: string | null;
      created_at?: string;
      updated_at?: string;
      logo_path?: string | null;
    };
    Relations: {
      customer_tags: { table: "customer_tags"; kind: "many"; nullable: true };
      organization: { table: "organizations"; kind: "one"; nullable: false };
      primary_contact: { table: "contacts"; kind: "one"; nullable: true };
      locations: { table: "locations"; kind: "many"; nullable: true };
      notes: { table: "notes"; kind: "many"; nullable: true };
    };
    PrimaryKey: "id";
    UniqueKeys: {
      customers_id_organization_id_key: readonly ["id", "organization_id"];
      customers_organization_id_kvk_key: readonly ["organization_id", "kvk"];
    };
    Checks: "customers_archived_check" | "customers_name_check" | "customers_status_check";
    ForeignKeys: "customers_organization_id_fkey" | "customers_primary_contact_id_fkey";
    Flags: Record<never, never>;
  };
  locations: {
    Row: {
      id: string;
      organization_id: string;
      customer_id: string;
      label: string;
      city: string | null;
      is_primary: boolean;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      organization_id: string;
      customer_id: string;
      label: string;
      city?: string | null;
      is_primary?: boolean;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      organization_id?: string;
      customer_id?: string;
      label?: string;
      city?: string | null;
      is_primary?: boolean;
      created_at?: string;
      updated_at?: string;
    };
    Relations: {
      customer: { table: "customers"; kind: "one"; nullable: false };
      organization: { table: "organizations"; kind: "one"; nullable: false };
    };
    PrimaryKey: "id";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "locations_customer_id_fkey" | "locations_organization_id_fkey";
    Flags: Record<never, never>;
  };
  memberships: {
    Row: {
      organization_id: string;
      user_id: string;
      role: "owner" | "admin" | "member";
      created_at: string;
      last_used_at: string | null;
    };
    Insert: {
      organization_id: string;
      user_id: string;
      role?: "owner" | "admin" | "member";
      created_at?: string;
      last_used_at?: string | null;
    };
    Update: {
      organization_id?: string;
      user_id?: string;
      role?: "owner" | "admin" | "member";
      created_at?: string;
      last_used_at?: string | null;
    };
    Relations: {
      organization: { table: "organizations"; kind: "one"; nullable: false };
    };
    PrimaryKey: "organization_id" | "user_id";
    UniqueKeys: Record<never, never>;
    Checks: "memberships_role_check";
    ForeignKeys: "memberships_organization_id_fkey" | "memberships_user_id_fkey";
    Flags: Record<never, never>;
  };
  notes: {
    Row: {
      id: number;
      organization_id: string;
      customer_id: string;
      kind: "call" | "meeting" | "email";
      body: string;
      attachments: Json | null;
      created_at: string;
      updated_at: string;
      embedding: string | null;
    };
    Insert: {
      id?: never;
      organization_id: string;
      customer_id: string;
      kind?: "call" | "meeting" | "email";
      body: string;
      attachments?: Json | null;
      created_at?: string;
      updated_at?: string;
      embedding?: string | null;
    };
    Update: {
      id?: never;
      organization_id?: string;
      customer_id?: string;
      kind?: "call" | "meeting" | "email";
      body?: string;
      attachments?: Json | null;
      created_at?: string;
      updated_at?: string;
      embedding?: string | null;
    };
    Relations: {
      customer: { table: "customers"; kind: "one"; nullable: false };
      organization: { table: "organizations"; kind: "one"; nullable: false };
    };
    PrimaryKey: "id";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "notes_customer_id_fkey" | "notes_organization_id_fkey";
    Flags: Record<never, never>;
  };
  organizations: {
    Row: {
      id: string;
      name: string;
      slug: string;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      name: string;
      slug: string;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      name?: string;
      slug?: string;
      created_at?: string;
      updated_at?: string;
    };
    Relations: {
      contacts: { table: "contacts"; kind: "many"; nullable: true };
      customer_tags: { table: "customer_tags"; kind: "many"; nullable: true };
      customers: { table: "customers"; kind: "many"; nullable: true };
      locations: { table: "locations"; kind: "many"; nullable: true };
      memberships: { table: "memberships"; kind: "many"; nullable: true };
      notes: { table: "notes"; kind: "many"; nullable: true };
      subscription: { table: "subscriptions"; kind: "one"; nullable: true };
      tags: { table: "tags"; kind: "many"; nullable: true };
    };
    PrimaryKey: "id";
    UniqueKeys: {
      organizations_slug_key: readonly ["slug"];
    };
    Checks: never;
    ForeignKeys: never;
    Flags: Record<never, never>;
  };
  plan_features: {
    Row: {
      plan_key: string;
      feature_key: string;
      included: boolean;
      value: Json | null;
    };
    Insert: {
      plan_key: string;
      feature_key: string;
      included?: boolean;
      value?: Json | null;
    };
    Update: {
      plan_key?: string;
      feature_key?: string;
      included?: boolean;
      value?: Json | null;
    };
    Relations: {
      plan: { table: "plans"; kind: "one"; nullable: false };
    };
    PrimaryKey: "plan_key" | "feature_key";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "plan_features_plan_key_fkey";
    Flags: Record<never, never>;
  };
  plans: {
    Row: {
      key: string;
      name: string;
      price_cents: number;
      position: number;
    };
    Insert: {
      key: string;
      name: string;
      price_cents?: number;
      position?: number;
    };
    Update: {
      key?: string;
      name?: string;
      price_cents?: number;
      position?: number;
    };
    Relations: {
      plan_features: { table: "plan_features"; kind: "many"; nullable: true };
      subscriptions: { table: "subscriptions"; kind: "many"; nullable: true };
    };
    PrimaryKey: "key";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: never;
    Flags: Record<never, never>;
  };
  subscriptions: {
    Row: {
      organization_id: string;
      plan_key: string;
      status: "active" | "trialing" | "past_due" | "canceled";
      current_period_end: string | null;
      updated_at: string;
    };
    Insert: {
      organization_id: string;
      plan_key: string;
      status?: "active" | "trialing" | "past_due" | "canceled";
      current_period_end?: string | null;
      updated_at?: string;
    };
    Update: {
      organization_id?: string;
      plan_key?: string;
      status?: "active" | "trialing" | "past_due" | "canceled";
      current_period_end?: string | null;
      updated_at?: string;
    };
    Relations: {
      organization: { table: "organizations"; kind: "one"; nullable: false };
      plan: { table: "plans"; kind: "one"; nullable: false };
    };
    PrimaryKey: "organization_id";
    UniqueKeys: Record<never, never>;
    Checks: "subscriptions_status_check";
    ForeignKeys: "subscriptions_organization_id_fkey" | "subscriptions_plan_key_fkey";
    Flags: Record<never, never>;
  };
  tags: {
    Row: {
      id: string;
      organization_id: string;
      name: string;
      color: "gray" | "red" | "green" | "blue";
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      organization_id: string;
      name: string;
      color?: "gray" | "red" | "green" | "blue";
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      organization_id?: string;
      name?: string;
      color?: "gray" | "red" | "green" | "blue";
      created_at?: string;
      updated_at?: string;
    };
    Relations: {
      customer_tags: { table: "customer_tags"; kind: "many"; nullable: true };
      organization: { table: "organizations"; kind: "one"; nullable: false };
    };
    PrimaryKey: "id";
    UniqueKeys: {
      tags_id_organization_id_key: readonly ["id", "organization_id"];
      tags_organization_id_name_key: readonly ["organization_id", "name"];
    };
    Checks: "tags_color_check";
    ForeignKeys: "tags_organization_id_fkey";
    Flags: Record<never, never>;
  };
};

export type Functions = {
  customer_note_counts: {
    Args: {
      p_customer_ids?: string[] | null;
    };
    Returns: { "customer_id": string | null; "last_note_at": string | null; "note_count": number | null }[];
  };
  customers_by_status: {
    Args: {
      p_limit?: number | null;
      p_status: string | null;
    };
    Returns: (Models["customers"]['Row'])[];
  };
  my_organizations: {
    Args: Record<never, never>;
    Returns: { "id": string | null; "last_used_at": string | null; "name": string | null; "plan": string | null; "role": string | null; "slug": string | null }[];
  };
  my_profile: {
    Args: Record<never, never>;
    Returns: { "avatar_path": string | null; "avatar_url": string | null; "email": string | null; "full_name": string | null; "username": string | null }[];
  };
  organization_invitations: {
    Args: {
      organization: string | null;
    };
    Returns: { "created_at": string | null; "email": string | null; "expires_at": string | null; "id": string | null; "invited_by": string | null; "role": string | null }[];
  };
  organization_members: {
    Args: {
      organization: string | null;
    };
    Returns: { "avatar_path": string | null; "avatar_url": string | null; "email": string | null; "full_name": string | null; "joined_at": string | null; "role": string | null; "user_id": string | null }[];
  };
  rs_workspace_summary: {
    Args: {
      p: Json | null;
    };
    Returns: Json;
  };
  search_notes: {
    Args: {
      k?: number | null;
      query: string | null;
    };
    Returns: (Models["notes"]['Row'])[];
  };
  search_notes_scores: {
    Args: {
      k?: number | null;
      query: string | null;
    };
    Returns: { "id": Json; "score": number | null }[];
  };
  set_my_avatar_path: {
    Args: {
      avatar_path: string | null;
    };
    Returns: undefined;
  };
  update_my_profile: {
    Args: {
      full_name: string | null;
    };
    Returns: undefined;
  };
};

export type TableName = keyof Models;
/** Constraint names for `isConflict`, `isCheck` and `isForeignKey`. */
export type UniqueConstraint = { [T in TableName]: Extract<keyof Models[T]['UniqueKeys'], string> }[TableName];
export type CheckConstraint = Models[TableName]['Checks'];
export type ForeignKeyConstraint = Models[TableName]['ForeignKeys'];
export type RowOf<T extends TableName> = Models[T]['Row'];
export type InsertOf<T extends TableName> = Models[T]['Insert'];
export type UpdateOf<T extends TableName> = Models[T]['Update'];
/** A `where` for `T` you can assign to one key at a time. */
export type WhereOf<T extends TableName> = MutableWhere<Models, T>;
/** An `orderBy` for `T`: one sort or a list, by column or to-one relation. */
export type OrderByOf<T extends TableName> = OrderByArg<Models, T>;
/** One sort term of `T`'s `orderBy`, by column or to-one relation. */
export type OrderTermOf<T extends TableName> = OrderByInput<Models, T>;

export const schema: Schema<Models, Database, Functions> = defineSchema(meta);
