// @generated by better-supabase gen. Do not edit; run `better-supabase gen` instead.
/* oxlint-disable */
/* eslint-disable */

import type { EnrichDatabase } from 'better-supabase';

import { defineSchema, type Schema } from 'better-supabase';

import type { Database as SupabaseDatabase } from './database.types.ts';

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = EnrichDatabase<
  SupabaseDatabase,
  {
    public: {
      customers: {
        status: 'lead' | 'active' | 'archived';
        metadata: { source?: string; tier?: 'free' | 'pro' };
      };
      tags: {
        color: 'gray' | 'red' | 'green' | 'blue';
      };
    };
  }
>;

export const noteKindValues = ['call', 'meeting', 'email'] as const;
export type NoteKind = (typeof noteKindValues)[number];
export const customersStatusValues = ['lead', 'active', 'archived'] as const;
export type CustomersStatus = (typeof customersStatusValues)[number];
export const tagsColorValues = ['gray', 'red', 'green', 'blue'] as const;
export type TagsColor = (typeof tagsColorValues)[number];

export type Models = {
  contacts: {
    Row: {
      id: string;
      organizationId: string;
      email: string;
      fullName: string | null;
      createdAt: string;
      updatedAt: string;
    };
    Insert: {
      id?: string;
      organizationId: string;
      email: string;
      fullName?: string | null;
      createdAt?: string;
      updatedAt?: string;
    };
    Update: {
      id?: string;
      organizationId?: string;
      email?: string;
      fullName?: string | null;
      createdAt?: string;
      updatedAt?: string;
    };
    Relations: {
      organization: { table: 'organizations'; kind: 'one'; nullable: false };
      customers: { table: 'customers'; kind: 'many'; nullable: true };
    };
    PrimaryKey: 'id';
    UniqueKeys: Record<never, never>;
    Flags: {
      timestamps: true;
      tenant: 'organizationId';
    };
  };
  customerTags: {
    Row: {
      customerId: string;
      tagId: string;
      organizationId: string;
    };
    Insert: {
      customerId: string;
      tagId: string;
      organizationId: string;
    };
    Update: {
      customerId?: string;
      tagId?: string;
      organizationId?: string;
    };
    Relations: {
      customer: { table: 'customers'; kind: 'one'; nullable: false };
      organization: { table: 'organizations'; kind: 'one'; nullable: false };
      tag: { table: 'tags'; kind: 'one'; nullable: false };
    };
    PrimaryKey: 'customerId' | 'tagId';
    UniqueKeys: Record<never, never>;
    Flags: {
      tenant: 'organizationId';
    };
  };
  customers: {
    Row: {
      id: string;
      organizationId: string;
      name: string;
      kvk: string | null;
      status: 'lead' | 'active' | 'archived';
      primaryContactId: string | null;
      metadata: { source?: string; tier?: 'free' | 'pro' };
      createdBy: string | null;
      updatedBy: string | null;
      archivedAt: string | null;
      createdAt: string;
      updatedAt: string;
    };
    Insert: {
      id?: string;
      organizationId: string;
      name: string;
      kvk?: string | null;
      status?: 'lead' | 'active' | 'archived';
      primaryContactId?: string | null;
      metadata?: { source?: string; tier?: 'free' | 'pro' };
      createdBy?: string | null;
      updatedBy?: string | null;
      archivedAt?: string | null;
      createdAt?: string;
      updatedAt?: string;
    };
    Update: {
      id?: string;
      organizationId?: string;
      name?: string;
      kvk?: string | null;
      status?: 'lead' | 'active' | 'archived';
      primaryContactId?: string | null;
      metadata?: { source?: string; tier?: 'free' | 'pro' };
      createdBy?: string | null;
      updatedBy?: string | null;
      archivedAt?: string | null;
      createdAt?: string;
      updatedAt?: string;
    };
    Relations: {
      customerTags: { table: 'customerTags'; kind: 'many'; nullable: true };
      organization: { table: 'organizations'; kind: 'one'; nullable: false };
      primaryContact: { table: 'contacts'; kind: 'one'; nullable: true };
      locations: { table: 'locations'; kind: 'many'; nullable: true };
      notes: { table: 'notes'; kind: 'many'; nullable: true };
    };
    PrimaryKey: 'id';
    UniqueKeys: {
      customers_organization_id_kvk_key: readonly ['organizationId', 'kvk'];
    };
    Flags: {
      softDelete: 'archivedAt';
      timestamps: true;
      tenant: 'organizationId';
      actor: true;
    };
  };
  locations: {
    Row: {
      id: string;
      organizationId: string;
      customerId: string;
      label: string;
      city: string | null;
      isPrimary: boolean;
      createdAt: string;
      updatedAt: string;
    };
    Insert: {
      id?: string;
      organizationId: string;
      customerId: string;
      label: string;
      city?: string | null;
      isPrimary?: boolean;
      createdAt?: string;
      updatedAt?: string;
    };
    Update: {
      id?: string;
      organizationId?: string;
      customerId?: string;
      label?: string;
      city?: string | null;
      isPrimary?: boolean;
      createdAt?: string;
      updatedAt?: string;
    };
    Relations: {
      customer: { table: 'customers'; kind: 'one'; nullable: false };
      organization: { table: 'organizations'; kind: 'one'; nullable: false };
    };
    PrimaryKey: 'id';
    UniqueKeys: Record<never, never>;
    Flags: {
      timestamps: true;
      tenant: 'organizationId';
    };
  };
  notes: {
    Row: {
      id: number;
      organizationId: string;
      customerId: string;
      kind: 'call' | 'meeting' | 'email';
      body: string;
      attachments: Json | null;
      createdAt: string;
      updatedAt: string;
    };
    Insert: {
      id?: never;
      organizationId: string;
      customerId: string;
      kind?: 'call' | 'meeting' | 'email';
      body: string;
      attachments?: Json | null;
      createdAt?: string;
      updatedAt?: string;
    };
    Update: {
      id?: never;
      organizationId?: string;
      customerId?: string;
      kind?: 'call' | 'meeting' | 'email';
      body?: string;
      attachments?: Json | null;
      createdAt?: string;
      updatedAt?: string;
    };
    Relations: {
      customer: { table: 'customers'; kind: 'one'; nullable: false };
      organization: { table: 'organizations'; kind: 'one'; nullable: false };
    };
    PrimaryKey: 'id';
    UniqueKeys: Record<never, never>;
    Flags: {
      timestamps: true;
      tenant: 'organizationId';
    };
  };
  organizations: {
    Row: {
      id: string;
      name: string;
      slug: string;
      createdAt: string;
      updatedAt: string;
    };
    Insert: {
      id?: string;
      name: string;
      slug: string;
      createdAt?: string;
      updatedAt?: string;
    };
    Update: {
      id?: string;
      name?: string;
      slug?: string;
      createdAt?: string;
      updatedAt?: string;
    };
    Relations: {
      contacts: { table: 'contacts'; kind: 'many'; nullable: true };
      customerTags: { table: 'customerTags'; kind: 'many'; nullable: true };
      customers: { table: 'customers'; kind: 'many'; nullable: true };
      locations: { table: 'locations'; kind: 'many'; nullable: true };
      notes: { table: 'notes'; kind: 'many'; nullable: true };
      tags: { table: 'tags'; kind: 'many'; nullable: true };
    };
    PrimaryKey: 'id';
    UniqueKeys: {
      organizations_slug_key: readonly ['slug'];
    };
    Flags: {
      timestamps: true;
    };
  };
  tags: {
    Row: {
      id: string;
      organizationId: string;
      name: string;
      color: 'gray' | 'red' | 'green' | 'blue';
    };
    Insert: {
      id?: string;
      organizationId: string;
      name: string;
      color?: 'gray' | 'red' | 'green' | 'blue';
    };
    Update: {
      id?: string;
      organizationId?: string;
      name?: string;
      color?: 'gray' | 'red' | 'green' | 'blue';
    };
    Relations: {
      customerTags: { table: 'customerTags'; kind: 'many'; nullable: true };
      organization: { table: 'organizations'; kind: 'one'; nullable: false };
    };
    PrimaryKey: 'id';
    UniqueKeys: {
      tags_organization_id_name_key: readonly ['organizationId', 'name'];
    };
    Flags: {
      tenant: 'organizationId';
    };
  };
};

export type Functions = Record<never, never>;

export type TableName = keyof Models;
export type RowOf<T extends TableName> = Models[T]['Row'];
export type InsertOf<T extends TableName> = Models[T]['Insert'];
export type UpdateOf<T extends TableName> = Models[T]['Update'];

/** Bucket configs for `defineBucket` from `better-supabase/storage`. */
export const buckets = {
  customerLogos: {
    id: 'customer-logos',
    public: false,
    path: '{orgId}/{customerId}/logo/{version}.webp',
    policy: 'tenant',
    fileSizeLimit: '5MiB',
    allowedMimeTypes: ['image/png', 'image/jpeg', 'image/webp'],
  },
} as const;

/** Topic templates for `defineTopic` from `better-supabase/realtime`. */
export const topics = {
  notifications: 'org:{orgId}:notifications:{userId}',
  customers: 'org:{orgId}:customers',
} as const;

export const schema: Schema<Models, Database, Functions> = defineSchema({
  version: 1,
  casing: 'camel',
  tables: {
    contacts: {
      key: 'contacts',
      name: 'contacts',
      schema: 'public',
      kind: 'table',
      columns: {
        id: {
          db: 'id',
          type: 'uuid',
          nullable: false,
          hasDefault: true,
        },
        organizationId: {
          db: 'organization_id',
          type: 'uuid',
          nullable: false,
          hasDefault: false,
        },
        email: {
          db: 'email',
          type: 'text',
          nullable: false,
          hasDefault: false,
        },
        fullName: {
          db: 'full_name',
          type: 'text',
          nullable: true,
          hasDefault: false,
        },
        createdAt: {
          db: 'created_at',
          type: 'timestamptz',
          nullable: false,
          hasDefault: true,
        },
        updatedAt: {
          db: 'updated_at',
          type: 'timestamptz',
          nullable: false,
          hasDefault: true,
        },
      },
      primaryKey: ['id'],
      uniqueKeys: {},
      relations: {
        organization: {
          table: 'organizations',
          kind: 'one',
          nullable: false,
          foreignKey: 'contacts_organization_id_fkey',
          columns: ['organizationId'],
          references: ['id'],
          direction: 'forward',
        },
        customers: {
          table: 'customers',
          kind: 'many',
          nullable: true,
          foreignKey: 'customers_primary_contact_id_fkey',
          columns: ['id'],
          references: ['primaryContactId'],
          direction: 'reverse',
        },
      },
      flags: {
        timestamps: {
          createdAt: 'createdAt',
          updatedAt: 'updatedAt',
        },
        tenant: 'organizationId',
      },
    },
    customerTags: {
      key: 'customerTags',
      name: 'customer_tags',
      schema: 'public',
      kind: 'table',
      columns: {
        customerId: {
          db: 'customer_id',
          type: 'uuid',
          nullable: false,
          hasDefault: false,
        },
        tagId: {
          db: 'tag_id',
          type: 'uuid',
          nullable: false,
          hasDefault: false,
        },
        organizationId: {
          db: 'organization_id',
          type: 'uuid',
          nullable: false,
          hasDefault: false,
        },
      },
      primaryKey: ['customerId', 'tagId'],
      uniqueKeys: {},
      relations: {
        customer: {
          table: 'customers',
          kind: 'one',
          nullable: false,
          foreignKey: 'customer_tags_customer_id_fkey',
          columns: ['customerId'],
          references: ['id'],
          direction: 'forward',
        },
        organization: {
          table: 'organizations',
          kind: 'one',
          nullable: false,
          foreignKey: 'customer_tags_organization_id_fkey',
          columns: ['organizationId'],
          references: ['id'],
          direction: 'forward',
        },
        tag: {
          table: 'tags',
          kind: 'one',
          nullable: false,
          foreignKey: 'customer_tags_tag_id_fkey',
          columns: ['tagId'],
          references: ['id'],
          direction: 'forward',
        },
      },
      flags: {
        tenant: 'organizationId',
      },
    },
    customers: {
      key: 'customers',
      name: 'customers',
      schema: 'public',
      kind: 'table',
      columns: {
        id: {
          db: 'id',
          type: 'uuid',
          nullable: false,
          hasDefault: true,
        },
        organizationId: {
          db: 'organization_id',
          type: 'uuid',
          nullable: false,
          hasDefault: false,
        },
        name: {
          db: 'name',
          type: 'text',
          nullable: false,
          hasDefault: false,
        },
        kvk: {
          db: 'kvk',
          type: 'text',
          nullable: true,
          hasDefault: false,
        },
        status: {
          db: 'status',
          type: 'text',
          nullable: false,
          hasDefault: true,
          enum: ['lead', 'active', 'archived'],
        },
        primaryContactId: {
          db: 'primary_contact_id',
          type: 'uuid',
          nullable: true,
          hasDefault: false,
        },
        metadata: {
          db: 'metadata',
          type: 'jsonb',
          nullable: false,
          hasDefault: true,
          json: true,
        },
        createdBy: {
          db: 'created_by',
          type: 'uuid',
          nullable: true,
          hasDefault: false,
        },
        updatedBy: {
          db: 'updated_by',
          type: 'uuid',
          nullable: true,
          hasDefault: false,
        },
        archivedAt: {
          db: 'archived_at',
          type: 'timestamptz',
          nullable: true,
          hasDefault: false,
        },
        createdAt: {
          db: 'created_at',
          type: 'timestamptz',
          nullable: false,
          hasDefault: true,
        },
        updatedAt: {
          db: 'updated_at',
          type: 'timestamptz',
          nullable: false,
          hasDefault: true,
        },
      },
      primaryKey: ['id'],
      uniqueKeys: {
        customers_organization_id_kvk_key: ['organizationId', 'kvk'],
      },
      relations: {
        customerTags: {
          table: 'customerTags',
          kind: 'many',
          nullable: true,
          foreignKey: 'customer_tags_customer_id_fkey',
          columns: ['id'],
          references: ['customerId'],
          direction: 'reverse',
        },
        organization: {
          table: 'organizations',
          kind: 'one',
          nullable: false,
          foreignKey: 'customers_organization_id_fkey',
          columns: ['organizationId'],
          references: ['id'],
          direction: 'forward',
        },
        primaryContact: {
          table: 'contacts',
          kind: 'one',
          nullable: true,
          foreignKey: 'customers_primary_contact_id_fkey',
          columns: ['primaryContactId'],
          references: ['id'],
          direction: 'forward',
        },
        locations: {
          table: 'locations',
          kind: 'many',
          nullable: true,
          foreignKey: 'locations_customer_id_fkey',
          columns: ['id'],
          references: ['customerId'],
          direction: 'reverse',
        },
        notes: {
          table: 'notes',
          kind: 'many',
          nullable: true,
          foreignKey: 'notes_customer_id_fkey',
          columns: ['id'],
          references: ['customerId'],
          direction: 'reverse',
        },
      },
      flags: {
        softDelete: 'archivedAt',
        timestamps: {
          createdAt: 'createdAt',
          updatedAt: 'updatedAt',
        },
        tenant: 'organizationId',
        actor: {
          createdBy: 'createdBy',
          updatedBy: 'updatedBy',
        },
      },
    },
    locations: {
      key: 'locations',
      name: 'locations',
      schema: 'public',
      kind: 'table',
      columns: {
        id: {
          db: 'id',
          type: 'uuid',
          nullable: false,
          hasDefault: true,
        },
        organizationId: {
          db: 'organization_id',
          type: 'uuid',
          nullable: false,
          hasDefault: false,
        },
        customerId: {
          db: 'customer_id',
          type: 'uuid',
          nullable: false,
          hasDefault: false,
        },
        label: {
          db: 'label',
          type: 'text',
          nullable: false,
          hasDefault: false,
        },
        city: {
          db: 'city',
          type: 'text',
          nullable: true,
          hasDefault: false,
        },
        isPrimary: {
          db: 'is_primary',
          type: 'bool',
          nullable: false,
          hasDefault: true,
        },
        createdAt: {
          db: 'created_at',
          type: 'timestamptz',
          nullable: false,
          hasDefault: true,
        },
        updatedAt: {
          db: 'updated_at',
          type: 'timestamptz',
          nullable: false,
          hasDefault: true,
        },
      },
      primaryKey: ['id'],
      uniqueKeys: {},
      relations: {
        customer: {
          table: 'customers',
          kind: 'one',
          nullable: false,
          foreignKey: 'locations_customer_id_fkey',
          columns: ['customerId'],
          references: ['id'],
          direction: 'forward',
        },
        organization: {
          table: 'organizations',
          kind: 'one',
          nullable: false,
          foreignKey: 'locations_organization_id_fkey',
          columns: ['organizationId'],
          references: ['id'],
          direction: 'forward',
        },
      },
      flags: {
        timestamps: {
          createdAt: 'createdAt',
          updatedAt: 'updatedAt',
        },
        tenant: 'organizationId',
      },
    },
    notes: {
      key: 'notes',
      name: 'notes',
      schema: 'public',
      kind: 'table',
      columns: {
        id: {
          db: 'id',
          type: 'int8',
          nullable: false,
          hasDefault: true,
          generated: true,
        },
        organizationId: {
          db: 'organization_id',
          type: 'uuid',
          nullable: false,
          hasDefault: false,
        },
        customerId: {
          db: 'customer_id',
          type: 'uuid',
          nullable: false,
          hasDefault: false,
        },
        kind: {
          db: 'kind',
          type: 'note_kind',
          nullable: false,
          hasDefault: true,
          enum: ['call', 'meeting', 'email'],
        },
        body: {
          db: 'body',
          type: 'text',
          nullable: false,
          hasDefault: false,
        },
        attachments: {
          db: 'attachments',
          type: 'jsonb',
          nullable: true,
          hasDefault: false,
          json: true,
        },
        createdAt: {
          db: 'created_at',
          type: 'timestamptz',
          nullable: false,
          hasDefault: true,
        },
        updatedAt: {
          db: 'updated_at',
          type: 'timestamptz',
          nullable: false,
          hasDefault: true,
        },
      },
      primaryKey: ['id'],
      uniqueKeys: {},
      relations: {
        customer: {
          table: 'customers',
          kind: 'one',
          nullable: false,
          foreignKey: 'notes_customer_id_fkey',
          columns: ['customerId'],
          references: ['id'],
          direction: 'forward',
        },
        organization: {
          table: 'organizations',
          kind: 'one',
          nullable: false,
          foreignKey: 'notes_organization_id_fkey',
          columns: ['organizationId'],
          references: ['id'],
          direction: 'forward',
        },
      },
      flags: {
        timestamps: {
          createdAt: 'createdAt',
          updatedAt: 'updatedAt',
        },
        tenant: 'organizationId',
      },
    },
    organizations: {
      key: 'organizations',
      name: 'organizations',
      schema: 'public',
      kind: 'table',
      columns: {
        id: {
          db: 'id',
          type: 'uuid',
          nullable: false,
          hasDefault: true,
        },
        name: {
          db: 'name',
          type: 'text',
          nullable: false,
          hasDefault: false,
        },
        slug: {
          db: 'slug',
          type: 'text',
          nullable: false,
          hasDefault: false,
        },
        createdAt: {
          db: 'created_at',
          type: 'timestamptz',
          nullable: false,
          hasDefault: true,
        },
        updatedAt: {
          db: 'updated_at',
          type: 'timestamptz',
          nullable: false,
          hasDefault: true,
        },
      },
      primaryKey: ['id'],
      uniqueKeys: {
        organizations_slug_key: ['slug'],
      },
      relations: {
        contacts: {
          table: 'contacts',
          kind: 'many',
          nullable: true,
          foreignKey: 'contacts_organization_id_fkey',
          columns: ['id'],
          references: ['organizationId'],
          direction: 'reverse',
        },
        customerTags: {
          table: 'customerTags',
          kind: 'many',
          nullable: true,
          foreignKey: 'customer_tags_organization_id_fkey',
          columns: ['id'],
          references: ['organizationId'],
          direction: 'reverse',
        },
        customers: {
          table: 'customers',
          kind: 'many',
          nullable: true,
          foreignKey: 'customers_organization_id_fkey',
          columns: ['id'],
          references: ['organizationId'],
          direction: 'reverse',
        },
        locations: {
          table: 'locations',
          kind: 'many',
          nullable: true,
          foreignKey: 'locations_organization_id_fkey',
          columns: ['id'],
          references: ['organizationId'],
          direction: 'reverse',
        },
        notes: {
          table: 'notes',
          kind: 'many',
          nullable: true,
          foreignKey: 'notes_organization_id_fkey',
          columns: ['id'],
          references: ['organizationId'],
          direction: 'reverse',
        },
        tags: {
          table: 'tags',
          kind: 'many',
          nullable: true,
          foreignKey: 'tags_organization_id_fkey',
          columns: ['id'],
          references: ['organizationId'],
          direction: 'reverse',
        },
      },
      flags: {
        timestamps: {
          createdAt: 'createdAt',
          updatedAt: 'updatedAt',
        },
      },
    },
    tags: {
      key: 'tags',
      name: 'tags',
      schema: 'public',
      kind: 'table',
      columns: {
        id: {
          db: 'id',
          type: 'uuid',
          nullable: false,
          hasDefault: true,
        },
        organizationId: {
          db: 'organization_id',
          type: 'uuid',
          nullable: false,
          hasDefault: false,
        },
        name: {
          db: 'name',
          type: 'text',
          nullable: false,
          hasDefault: false,
        },
        color: {
          db: 'color',
          type: 'text',
          nullable: false,
          hasDefault: true,
          enum: ['gray', 'red', 'green', 'blue'],
        },
      },
      primaryKey: ['id'],
      uniqueKeys: {
        tags_organization_id_name_key: ['organizationId', 'name'],
      },
      relations: {
        customerTags: {
          table: 'customerTags',
          kind: 'many',
          nullable: true,
          foreignKey: 'customer_tags_tag_id_fkey',
          columns: ['id'],
          references: ['tagId'],
          direction: 'reverse',
        },
        organization: {
          table: 'organizations',
          kind: 'one',
          nullable: false,
          foreignKey: 'tags_organization_id_fkey',
          columns: ['organizationId'],
          references: ['id'],
          direction: 'forward',
        },
      },
      flags: {
        tenant: 'organizationId',
      },
    },
  },
  enums: {
    note_kind: ['call', 'meeting', 'email'],
  },
  functions: {},
  buckets: {
    customerLogos: {
      id: 'customer-logos',
      public: false,
      path: '{orgId}/{customerId}/logo/{version}.webp',
      policy: 'tenant',
      fileSizeLimit: '5MiB',
      allowedMimeTypes: ['image/png', 'image/jpeg', 'image/webp'],
    },
  },
  topics: {
    notifications: 'org:{orgId}:notifications:{userId}',
    customers: 'org:{orgId}:customers',
  },
});
