// Generated by better-supabase. Do not edit; run `better-supabase gen`.

import { z } from "zod";

import type { InsertOf, RowOf, UpdateOf } from "./generated-camel.ts";

export const contactsRow: z.ZodType<RowOf<'contacts'>> = z.object({
  id: z.guid(),
  organizationId: z.guid(),
  email: z.string(),
  fullName: z.string().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
}).meta({ title: "Contacts" });
export const contactsInsert: z.ZodType<InsertOf<'contacts'>> = z.object({
  id: z.guid().exactOptional(),
  organizationId: z.guid(),
  email: z.string(),
  fullName: z.string().nullable().exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
}).meta({ title: "Contacts insert" });
export const contactsUpdate: z.ZodType<UpdateOf<'contacts'>> = z.object({
  id: z.guid().exactOptional(),
  organizationId: z.guid().exactOptional(),
  email: z.string().exactOptional(),
  fullName: z.string().nullable().exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
}).meta({ title: "Contacts update" });

export const customerTagsRow: z.ZodType<RowOf<'customerTags'>> = z.object({
  customerId: z.guid(),
  tagId: z.guid(),
  organizationId: z.guid(),
  createdAt: z.iso.datetime({ offset: true }),
}).meta({ title: "Customer tags" });
export const customerTagsInsert: z.ZodType<InsertOf<'customerTags'>> = z.object({
  customerId: z.guid(),
  tagId: z.guid(),
  organizationId: z.guid(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
}).meta({ title: "Customer tags insert" });
export const customerTagsUpdate: z.ZodType<UpdateOf<'customerTags'>> = z.object({
  customerId: z.guid().exactOptional(),
  tagId: z.guid().exactOptional(),
  organizationId: z.guid().exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
}).meta({ title: "Customer tags update" });

export const customersRow: z.ZodType<RowOf<'customers'>> = z.object({
  id: z.guid(),
  organizationId: z.guid(),
  name: z.string().min(1).max(200).meta({ description: "Trading name.", examples: ["Acme B.V."] }),
  kvk: z.string().nullable().meta({ description: "Chamber of Commerce (KvK) number.", examples: ["12345678"] }),
  status: z.enum(["lead", "active", "archived"]),
  primaryContactId: z.guid().nullable(),
  metadata: z.custom<NonNullable<RowOf<'customers'>['metadata']>>((value) => value !== undefined),
  createdBy: z.guid().nullable(),
  updatedBy: z.guid().nullable(),
  archivedAt: z.iso.datetime({ offset: true }).nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
  logoPath: (z.string() as unknown as z.ZodType<NonNullable<RowOf<'customers'>['logoPath']>>).nullable(),
}).meta({ title: "Customers", description: "Companies the organization sells to." });
export const customersInsert: z.ZodType<InsertOf<'customers'>> = z.object({
  id: z.guid().exactOptional(),
  organizationId: z.guid(),
  name: z.string().min(1).max(200).meta({ description: "Trading name.", examples: ["Acme B.V."] }),
  kvk: z.string().nullable().meta({ description: "Chamber of Commerce (KvK) number.", examples: ["12345678"] }).exactOptional(),
  status: z.enum(["lead", "active", "archived"]).exactOptional(),
  primaryContactId: z.guid().nullable().exactOptional(),
  metadata: z.custom<NonNullable<RowOf<'customers'>['metadata']>>((value) => value !== undefined).exactOptional(),
  createdBy: z.guid().nullable().exactOptional(),
  updatedBy: z.guid().nullable().exactOptional(),
  archivedAt: z.iso.datetime({ offset: true }).nullable().exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
  logoPath: (z.string() as unknown as z.ZodType<NonNullable<RowOf<'customers'>['logoPath']>>).nullable().exactOptional(),
}).meta({ title: "Customers insert", description: "Companies the organization sells to." });
export const customersUpdate: z.ZodType<UpdateOf<'customers'>> = z.object({
  id: z.guid().exactOptional(),
  organizationId: z.guid().exactOptional(),
  name: z.string().min(1).max(200).meta({ description: "Trading name.", examples: ["Acme B.V."] }).exactOptional(),
  kvk: z.string().nullable().meta({ description: "Chamber of Commerce (KvK) number.", examples: ["12345678"] }).exactOptional(),
  status: z.enum(["lead", "active", "archived"]).exactOptional(),
  primaryContactId: z.guid().nullable().exactOptional(),
  metadata: z.custom<NonNullable<RowOf<'customers'>['metadata']>>((value) => value !== undefined).exactOptional(),
  createdBy: z.guid().nullable().exactOptional(),
  updatedBy: z.guid().nullable().exactOptional(),
  archivedAt: z.iso.datetime({ offset: true }).nullable().exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
  logoPath: (z.string() as unknown as z.ZodType<NonNullable<RowOf<'customers'>['logoPath']>>).nullable().exactOptional(),
}).meta({ title: "Customers update", description: "Companies the organization sells to." });

export const locationsRow: z.ZodType<RowOf<'locations'>> = z.object({
  id: z.guid(),
  organizationId: z.guid(),
  customerId: z.guid(),
  label: z.string(),
  city: z.string().nullable(),
  isPrimary: z.boolean(),
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
}).meta({ title: "Locations" });
export const locationsInsert: z.ZodType<InsertOf<'locations'>> = z.object({
  id: z.guid().exactOptional(),
  organizationId: z.guid(),
  customerId: z.guid(),
  label: z.string(),
  city: z.string().nullable().exactOptional(),
  isPrimary: z.boolean().exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
}).meta({ title: "Locations insert" });
export const locationsUpdate: z.ZodType<UpdateOf<'locations'>> = z.object({
  id: z.guid().exactOptional(),
  organizationId: z.guid().exactOptional(),
  customerId: z.guid().exactOptional(),
  label: z.string().exactOptional(),
  city: z.string().nullable().exactOptional(),
  isPrimary: z.boolean().exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
}).meta({ title: "Locations update" });

export const membershipsRow: z.ZodType<RowOf<'memberships'>> = z.object({
  organizationId: z.guid(),
  userId: z.guid(),
  role: z.enum(["owner", "admin", "member"]),
  createdAt: z.iso.datetime({ offset: true }),
  lastUsedAt: z.iso.datetime({ offset: true }).nullable(),
}).meta({ title: "Memberships" });
export const membershipsInsert: z.ZodType<InsertOf<'memberships'>> = z.object({
  organizationId: z.guid(),
  userId: z.guid(),
  role: z.enum(["owner", "admin", "member"]).exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  lastUsedAt: z.iso.datetime({ offset: true }).nullable().exactOptional(),
}).meta({ title: "Memberships insert" });
export const membershipsUpdate: z.ZodType<UpdateOf<'memberships'>> = z.object({
  organizationId: z.guid().exactOptional(),
  userId: z.guid().exactOptional(),
  role: z.enum(["owner", "admin", "member"]).exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  lastUsedAt: z.iso.datetime({ offset: true }).nullable().exactOptional(),
}).meta({ title: "Memberships update" });

export const notesRow: z.ZodType<RowOf<'notes'>> = z.object({
  id: z.int(),
  organizationId: z.guid(),
  customerId: z.guid(),
  kind: z.enum(["call", "meeting", "email"]),
  body: z.string(),
  attachments: z.json().nullable(),
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
  embedding: z.string().nullable(),
}).meta({ title: "Notes" });
export const notesInsert: z.ZodType<InsertOf<'notes'>> = z.object({
  organizationId: z.guid(),
  customerId: z.guid(),
  kind: z.enum(["call", "meeting", "email"]).exactOptional(),
  body: z.string(),
  attachments: z.json().nullable().exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
  embedding: z.string().nullable().exactOptional(),
}).meta({ title: "Notes insert" });
export const notesUpdate: z.ZodType<UpdateOf<'notes'>> = z.object({
  organizationId: z.guid().exactOptional(),
  customerId: z.guid().exactOptional(),
  kind: z.enum(["call", "meeting", "email"]).exactOptional(),
  body: z.string().exactOptional(),
  attachments: z.json().nullable().exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
  embedding: z.string().nullable().exactOptional(),
}).meta({ title: "Notes update" });

export const organizationsRow: z.ZodType<RowOf<'organizations'>> = z.object({
  id: z.guid(),
  name: z.string(),
  slug: z.string(),
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
}).meta({ title: "Organizations" });
export const organizationsInsert: z.ZodType<InsertOf<'organizations'>> = z.object({
  id: z.guid().exactOptional(),
  name: z.string(),
  slug: z.string(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
}).meta({ title: "Organizations insert" });
export const organizationsUpdate: z.ZodType<UpdateOf<'organizations'>> = z.object({
  id: z.guid().exactOptional(),
  name: z.string().exactOptional(),
  slug: z.string().exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
}).meta({ title: "Organizations update" });

export const planFeaturesRow: z.ZodType<RowOf<'planFeatures'>> = z.object({
  planKey: z.string(),
  featureKey: z.string(),
  included: z.boolean(),
  value: z.json().nullable(),
}).meta({ title: "Plan features" });
export const planFeaturesInsert: z.ZodType<InsertOf<'planFeatures'>> = z.object({
  planKey: z.string(),
  featureKey: z.string(),
  included: z.boolean().exactOptional(),
  value: z.json().nullable().exactOptional(),
}).meta({ title: "Plan features insert" });
export const planFeaturesUpdate: z.ZodType<UpdateOf<'planFeatures'>> = z.object({
  planKey: z.string().exactOptional(),
  featureKey: z.string().exactOptional(),
  included: z.boolean().exactOptional(),
  value: z.json().nullable().exactOptional(),
}).meta({ title: "Plan features update" });

export const plansRow: z.ZodType<RowOf<'plans'>> = z.object({
  key: z.string(),
  name: z.string(),
  priceCents: z.int(),
  position: z.int(),
}).meta({ title: "Plans" });
export const plansInsert: z.ZodType<InsertOf<'plans'>> = z.object({
  key: z.string(),
  name: z.string(),
  priceCents: z.int().exactOptional(),
  position: z.int().exactOptional(),
}).meta({ title: "Plans insert" });
export const plansUpdate: z.ZodType<UpdateOf<'plans'>> = z.object({
  key: z.string().exactOptional(),
  name: z.string().exactOptional(),
  priceCents: z.int().exactOptional(),
  position: z.int().exactOptional(),
}).meta({ title: "Plans update" });

export const subscriptionsRow: z.ZodType<RowOf<'subscriptions'>> = z.object({
  organizationId: z.guid(),
  planKey: z.string(),
  status: z.enum(["active", "trialing", "past_due", "canceled"]),
  currentPeriodEnd: z.iso.datetime({ offset: true }).nullable(),
  updatedAt: z.iso.datetime({ offset: true }),
}).meta({ title: "Subscriptions" });
export const subscriptionsInsert: z.ZodType<InsertOf<'subscriptions'>> = z.object({
  organizationId: z.guid(),
  planKey: z.string(),
  status: z.enum(["active", "trialing", "past_due", "canceled"]).exactOptional(),
  currentPeriodEnd: z.iso.datetime({ offset: true }).nullable().exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
}).meta({ title: "Subscriptions insert" });
export const subscriptionsUpdate: z.ZodType<UpdateOf<'subscriptions'>> = z.object({
  organizationId: z.guid().exactOptional(),
  planKey: z.string().exactOptional(),
  status: z.enum(["active", "trialing", "past_due", "canceled"]).exactOptional(),
  currentPeriodEnd: z.iso.datetime({ offset: true }).nullable().exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
}).meta({ title: "Subscriptions update" });

export const tagsRow: z.ZodType<RowOf<'tags'>> = z.object({
  id: z.guid(),
  organizationId: z.guid(),
  name: z.string(),
  color: z.enum(["gray", "red", "green", "blue"]),
  createdAt: z.iso.datetime({ offset: true }),
  updatedAt: z.iso.datetime({ offset: true }),
}).meta({ title: "Tags" });
export const tagsInsert: z.ZodType<InsertOf<'tags'>> = z.object({
  id: z.guid().exactOptional(),
  organizationId: z.guid(),
  name: z.string(),
  color: z.enum(["gray", "red", "green", "blue"]).exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
}).meta({ title: "Tags insert" });
export const tagsUpdate: z.ZodType<UpdateOf<'tags'>> = z.object({
  id: z.guid().exactOptional(),
  organizationId: z.guid().exactOptional(),
  name: z.string().exactOptional(),
  color: z.enum(["gray", "red", "green", "blue"]).exactOptional(),
  createdAt: z.iso.datetime({ offset: true }).exactOptional(),
  updatedAt: z.iso.datetime({ offset: true }).exactOptional(),
}).meta({ title: "Tags update" });

/** Write validators for the validation plugin. */
export const validators: {
  readonly contacts: { readonly insert: typeof contactsInsert; readonly update: typeof contactsUpdate };
  readonly customerTags: { readonly insert: typeof customerTagsInsert; readonly update: typeof customerTagsUpdate };
  readonly customers: { readonly insert: typeof customersInsert; readonly update: typeof customersUpdate };
  readonly locations: { readonly insert: typeof locationsInsert; readonly update: typeof locationsUpdate };
  readonly memberships: { readonly insert: typeof membershipsInsert; readonly update: typeof membershipsUpdate };
  readonly notes: { readonly insert: typeof notesInsert; readonly update: typeof notesUpdate };
  readonly organizations: { readonly insert: typeof organizationsInsert; readonly update: typeof organizationsUpdate };
  readonly planFeatures: { readonly insert: typeof planFeaturesInsert; readonly update: typeof planFeaturesUpdate };
  readonly plans: { readonly insert: typeof plansInsert; readonly update: typeof plansUpdate };
  readonly subscriptions: { readonly insert: typeof subscriptionsInsert; readonly update: typeof subscriptionsUpdate };
  readonly tags: { readonly insert: typeof tagsInsert; readonly update: typeof tagsUpdate };
} = {
  contacts: { insert: contactsInsert, update: contactsUpdate },
  customerTags: { insert: customerTagsInsert, update: customerTagsUpdate },
  customers: { insert: customersInsert, update: customersUpdate },
  locations: { insert: locationsInsert, update: locationsUpdate },
  memberships: { insert: membershipsInsert, update: membershipsUpdate },
  notes: { insert: notesInsert, update: notesUpdate },
  organizations: { insert: organizationsInsert, update: organizationsUpdate },
  planFeatures: { insert: planFeaturesInsert, update: planFeaturesUpdate },
  plans: { insert: plansInsert, update: plansUpdate },
  subscriptions: { insert: subscriptionsInsert, update: subscriptionsUpdate },
  tags: { insert: tagsInsert, update: tagsUpdate },
};
