// Generated by better-supabase. Do not edit; run `better-supabase gen`.

import * as v from "valibot";

import type { InsertOf, Json, RowOf, UpdateOf } from "./generated-camel.ts";

const json: v.GenericSchema<Json> = v.lazy(() =>
  v.union([v.string(), v.number(), v.boolean(), v.null(), v.array(json), v.record(v.string(), v.optional(json))]),
);

export const contactsRow: v.GenericSchema<RowOf<'contacts'>> = v.pipe(v.object({
  id: v.pipe(v.string(), v.uuid()),
  organizationId: v.pipe(v.string(), v.uuid()),
  email: v.string(),
  fullName: v.nullable(v.string()),
  createdAt: v.pipe(v.string(), v.isoTimestamp()),
  updatedAt: v.pipe(v.string(), v.isoTimestamp()),
}), v.title("Contacts"));
export const contactsInsert: v.GenericSchema<InsertOf<'contacts'>> = v.pipe(v.object({
  id: v.exactOptional(v.pipe(v.string(), v.uuid())),
  organizationId: v.pipe(v.string(), v.uuid()),
  email: v.string(),
  fullName: v.exactOptional(v.nullable(v.string())),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
}), v.title("Contacts insert"));
export const contactsUpdate: v.GenericSchema<UpdateOf<'contacts'>> = v.pipe(v.object({
  id: v.exactOptional(v.pipe(v.string(), v.uuid())),
  organizationId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  email: v.exactOptional(v.string()),
  fullName: v.exactOptional(v.nullable(v.string())),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
}), v.title("Contacts update"));

export const customerTagsRow: v.GenericSchema<RowOf<'customerTags'>> = v.pipe(v.object({
  customerId: v.pipe(v.string(), v.uuid()),
  tagId: v.pipe(v.string(), v.uuid()),
  organizationId: v.pipe(v.string(), v.uuid()),
  createdAt: v.pipe(v.string(), v.isoTimestamp()),
}), v.title("Customer tags"));
export const customerTagsInsert: v.GenericSchema<InsertOf<'customerTags'>> = v.pipe(v.object({
  customerId: v.pipe(v.string(), v.uuid()),
  tagId: v.pipe(v.string(), v.uuid()),
  organizationId: v.pipe(v.string(), v.uuid()),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
}), v.title("Customer tags insert"));
export const customerTagsUpdate: v.GenericSchema<UpdateOf<'customerTags'>> = v.pipe(v.object({
  customerId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  tagId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  organizationId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
}), v.title("Customer tags update"));

export const customersRow: v.GenericSchema<RowOf<'customers'>> = v.pipe(v.object({
  id: v.pipe(v.string(), v.uuid()),
  organizationId: v.pipe(v.string(), v.uuid()),
  name: v.pipe(v.string(), v.minLength(1), v.maxLength(200), v.description("Trading name."), v.examples(["Acme B.V."])),
  kvk: v.pipe(v.nullable(v.string()), v.description("Chamber of Commerce (KvK) number."), v.examples(["12345678"])),
  status: v.picklist(["lead", "active", "archived"]),
  primaryContactId: v.nullable(v.pipe(v.string(), v.uuid())),
  metadata: v.custom<NonNullable<RowOf<'customers'>['metadata']>>((value) => value !== undefined),
  createdBy: v.nullable(v.pipe(v.string(), v.uuid())),
  updatedBy: v.nullable(v.pipe(v.string(), v.uuid())),
  archivedAt: v.nullable(v.pipe(v.string(), v.isoTimestamp())),
  createdAt: v.pipe(v.string(), v.isoTimestamp()),
  updatedAt: v.pipe(v.string(), v.isoTimestamp()),
  logoPath: v.nullable((v.string() as unknown as v.GenericSchema<NonNullable<RowOf<'customers'>['logoPath']>>)),
}), v.title("Customers"), v.description("Companies the organization sells to."));
export const customersInsert: v.GenericSchema<InsertOf<'customers'>> = v.pipe(v.object({
  id: v.exactOptional(v.pipe(v.string(), v.uuid())),
  organizationId: v.pipe(v.string(), v.uuid()),
  name: v.pipe(v.string(), v.minLength(1), v.maxLength(200), v.description("Trading name."), v.examples(["Acme B.V."])),
  kvk: v.exactOptional(v.pipe(v.nullable(v.string()), v.description("Chamber of Commerce (KvK) number."), v.examples(["12345678"]))),
  status: v.exactOptional(v.picklist(["lead", "active", "archived"])),
  primaryContactId: v.exactOptional(v.nullable(v.pipe(v.string(), v.uuid()))),
  metadata: v.exactOptional(v.custom<NonNullable<RowOf<'customers'>['metadata']>>((value) => value !== undefined)),
  createdBy: v.exactOptional(v.nullable(v.pipe(v.string(), v.uuid()))),
  updatedBy: v.exactOptional(v.nullable(v.pipe(v.string(), v.uuid()))),
  archivedAt: v.exactOptional(v.nullable(v.pipe(v.string(), v.isoTimestamp()))),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  logoPath: v.exactOptional(v.nullable((v.string() as unknown as v.GenericSchema<NonNullable<RowOf<'customers'>['logoPath']>>))),
}), v.title("Customers insert"), v.description("Companies the organization sells to."));
export const customersUpdate: v.GenericSchema<UpdateOf<'customers'>> = v.pipe(v.object({
  id: v.exactOptional(v.pipe(v.string(), v.uuid())),
  organizationId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  name: v.exactOptional(v.pipe(v.string(), v.minLength(1), v.maxLength(200), v.description("Trading name."), v.examples(["Acme B.V."]))),
  kvk: v.exactOptional(v.pipe(v.nullable(v.string()), v.description("Chamber of Commerce (KvK) number."), v.examples(["12345678"]))),
  status: v.exactOptional(v.picklist(["lead", "active", "archived"])),
  primaryContactId: v.exactOptional(v.nullable(v.pipe(v.string(), v.uuid()))),
  metadata: v.exactOptional(v.custom<NonNullable<RowOf<'customers'>['metadata']>>((value) => value !== undefined)),
  createdBy: v.exactOptional(v.nullable(v.pipe(v.string(), v.uuid()))),
  updatedBy: v.exactOptional(v.nullable(v.pipe(v.string(), v.uuid()))),
  archivedAt: v.exactOptional(v.nullable(v.pipe(v.string(), v.isoTimestamp()))),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  logoPath: v.exactOptional(v.nullable((v.string() as unknown as v.GenericSchema<NonNullable<RowOf<'customers'>['logoPath']>>))),
}), v.title("Customers update"), v.description("Companies the organization sells to."));

export const locationsRow: v.GenericSchema<RowOf<'locations'>> = v.pipe(v.object({
  id: v.pipe(v.string(), v.uuid()),
  organizationId: v.pipe(v.string(), v.uuid()),
  customerId: v.pipe(v.string(), v.uuid()),
  label: v.string(),
  city: v.nullable(v.string()),
  isPrimary: v.boolean(),
  createdAt: v.pipe(v.string(), v.isoTimestamp()),
  updatedAt: v.pipe(v.string(), v.isoTimestamp()),
}), v.title("Locations"));
export const locationsInsert: v.GenericSchema<InsertOf<'locations'>> = v.pipe(v.object({
  id: v.exactOptional(v.pipe(v.string(), v.uuid())),
  organizationId: v.pipe(v.string(), v.uuid()),
  customerId: v.pipe(v.string(), v.uuid()),
  label: v.string(),
  city: v.exactOptional(v.nullable(v.string())),
  isPrimary: v.exactOptional(v.boolean()),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
}), v.title("Locations insert"));
export const locationsUpdate: v.GenericSchema<UpdateOf<'locations'>> = v.pipe(v.object({
  id: v.exactOptional(v.pipe(v.string(), v.uuid())),
  organizationId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  customerId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  label: v.exactOptional(v.string()),
  city: v.exactOptional(v.nullable(v.string())),
  isPrimary: v.exactOptional(v.boolean()),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
}), v.title("Locations update"));

export const notesRow: v.GenericSchema<RowOf<'notes'>> = v.pipe(v.object({
  id: v.pipe(v.number(), v.integer()),
  organizationId: v.pipe(v.string(), v.uuid()),
  customerId: v.pipe(v.string(), v.uuid()),
  kind: v.picklist(["call", "meeting", "email"]),
  body: v.string(),
  attachments: v.nullable(json),
  createdAt: v.pipe(v.string(), v.isoTimestamp()),
  updatedAt: v.pipe(v.string(), v.isoTimestamp()),
  embedding: v.nullable(v.string()),
}), v.title("Notes"));
export const notesInsert: v.GenericSchema<InsertOf<'notes'>> = v.pipe(v.object({
  organizationId: v.pipe(v.string(), v.uuid()),
  customerId: v.pipe(v.string(), v.uuid()),
  kind: v.exactOptional(v.picklist(["call", "meeting", "email"])),
  body: v.string(),
  attachments: v.exactOptional(v.nullable(json)),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  embedding: v.exactOptional(v.nullable(v.string())),
}), v.title("Notes insert"));
export const notesUpdate: v.GenericSchema<UpdateOf<'notes'>> = v.pipe(v.object({
  organizationId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  customerId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  kind: v.exactOptional(v.picklist(["call", "meeting", "email"])),
  body: v.exactOptional(v.string()),
  attachments: v.exactOptional(v.nullable(json)),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  embedding: v.exactOptional(v.nullable(v.string())),
}), v.title("Notes update"));

export const notificationsRow: v.GenericSchema<RowOf<'notifications'>> = v.pipe(v.object({
  id: v.pipe(v.number(), v.integer()),
  organizationId: v.pipe(v.string(), v.uuid()),
  userId: v.pipe(v.string(), v.uuid()),
  title: v.string(),
  readAt: v.nullable(v.pipe(v.string(), v.isoTimestamp())),
  createdAt: v.pipe(v.string(), v.isoTimestamp()),
  updatedAt: v.pipe(v.string(), v.isoTimestamp()),
}), v.title("Notifications"));
export const notificationsInsert: v.GenericSchema<InsertOf<'notifications'>> = v.pipe(v.object({
  organizationId: v.pipe(v.string(), v.uuid()),
  userId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  title: v.string(),
  readAt: v.exactOptional(v.nullable(v.pipe(v.string(), v.isoTimestamp()))),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
}), v.title("Notifications insert"));
export const notificationsUpdate: v.GenericSchema<UpdateOf<'notifications'>> = v.pipe(v.object({
  organizationId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  userId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  title: v.exactOptional(v.string()),
  readAt: v.exactOptional(v.nullable(v.pipe(v.string(), v.isoTimestamp()))),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
}), v.title("Notifications update"));

export const organizationsRow: v.GenericSchema<RowOf<'organizations'>> = v.pipe(v.object({
  id: v.pipe(v.string(), v.uuid()),
  name: v.string(),
  slug: v.string(),
  createdAt: v.pipe(v.string(), v.isoTimestamp()),
  updatedAt: v.pipe(v.string(), v.isoTimestamp()),
}), v.title("Organizations"));
export const organizationsInsert: v.GenericSchema<InsertOf<'organizations'>> = v.pipe(v.object({
  id: v.exactOptional(v.pipe(v.string(), v.uuid())),
  name: v.string(),
  slug: v.string(),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
}), v.title("Organizations insert"));
export const organizationsUpdate: v.GenericSchema<UpdateOf<'organizations'>> = v.pipe(v.object({
  id: v.exactOptional(v.pipe(v.string(), v.uuid())),
  name: v.exactOptional(v.string()),
  slug: v.exactOptional(v.string()),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
}), v.title("Organizations update"));

export const tagsRow: v.GenericSchema<RowOf<'tags'>> = v.pipe(v.object({
  id: v.pipe(v.string(), v.uuid()),
  organizationId: v.pipe(v.string(), v.uuid()),
  name: v.string(),
  color: v.picklist(["gray", "red", "green", "blue"]),
  createdAt: v.pipe(v.string(), v.isoTimestamp()),
  updatedAt: v.pipe(v.string(), v.isoTimestamp()),
}), v.title("Tags"));
export const tagsInsert: v.GenericSchema<InsertOf<'tags'>> = v.pipe(v.object({
  id: v.exactOptional(v.pipe(v.string(), v.uuid())),
  organizationId: v.pipe(v.string(), v.uuid()),
  name: v.string(),
  color: v.exactOptional(v.picklist(["gray", "red", "green", "blue"])),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
}), v.title("Tags insert"));
export const tagsUpdate: v.GenericSchema<UpdateOf<'tags'>> = v.pipe(v.object({
  id: v.exactOptional(v.pipe(v.string(), v.uuid())),
  organizationId: v.exactOptional(v.pipe(v.string(), v.uuid())),
  name: v.exactOptional(v.string()),
  color: v.exactOptional(v.picklist(["gray", "red", "green", "blue"])),
  createdAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
  updatedAt: v.exactOptional(v.pipe(v.string(), v.isoTimestamp())),
}), v.title("Tags update"));

/** Write validators for the validation plugin. */
export const validators: {
  readonly contacts: { readonly insert: typeof contactsInsert; readonly update: typeof contactsUpdate };
  readonly customerTags: { readonly insert: typeof customerTagsInsert; readonly update: typeof customerTagsUpdate };
  readonly customers: { readonly insert: typeof customersInsert; readonly update: typeof customersUpdate };
  readonly locations: { readonly insert: typeof locationsInsert; readonly update: typeof locationsUpdate };
  readonly notes: { readonly insert: typeof notesInsert; readonly update: typeof notesUpdate };
  readonly notifications: { readonly insert: typeof notificationsInsert; readonly update: typeof notificationsUpdate };
  readonly organizations: { readonly insert: typeof organizationsInsert; readonly update: typeof organizationsUpdate };
  readonly tags: { readonly insert: typeof tagsInsert; readonly update: typeof tagsUpdate };
} = {
  contacts: { insert: contactsInsert, update: contactsUpdate },
  customerTags: { insert: customerTagsInsert, update: customerTagsUpdate },
  customers: { insert: customersInsert, update: customersUpdate },
  locations: { insert: locationsInsert, update: locationsUpdate },
  notes: { insert: notesInsert, update: notesUpdate },
  notifications: { insert: notificationsInsert, update: notificationsUpdate },
  organizations: { insert: organizationsInsert, update: organizationsUpdate },
  tags: { insert: tagsInsert, update: tagsUpdate },
};
