// @generated by better-supabase gen. Do not edit; run `better-supabase gen` instead.
/* oxlint-disable */
/* eslint-disable */

import { defineSchema, type Schema } from "../../src/index.ts";
import type { EnrichDatabase, StoragePath } from "../../src/index.ts";
import type { Database as SupabaseDatabase } from "./database.types.ts";

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = EnrichDatabase<
  SupabaseDatabase,
  {
    public: {
      customers: {
        status: "lead" | "active" | "archived";
        metadata: { source?: string; tier?: 'free' | 'pro' };
        logo_path: StoragePath<"customer-logos">;
      };
      tags: {
        color: "gray" | "red" | "green" | "blue";
      };
    };
  }
>;

export const noteKindValues = ["call", "meeting", "email"] as const;
export type NoteKind = (typeof noteKindValues)[number];
export const customersStatusValues = ["lead", "active", "archived"] as const;
export type CustomersStatus = (typeof customersStatusValues)[number];
export const tagsColorValues = ["gray", "red", "green", "blue"] as const;
export type TagsColor = (typeof tagsColorValues)[number];

export type Models = {
  contacts: {
    Row: {
      id: string;
      organization_id: string;
      email: string;
      full_name: string | null;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      organization_id: string;
      email: string;
      full_name?: string | null;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      organization_id?: string;
      email?: string;
      full_name?: string | null;
      created_at?: string;
      updated_at?: string;
    };
    Relations: {
      organization: { table: "organizations"; kind: "one"; nullable: false };
      customers: { table: "customers"; kind: "many"; nullable: true };
    };
    PrimaryKey: "id";
    UniqueKeys: {
      contacts_id_organization_id_key: readonly ["id", "organization_id"];
    };
    Checks: never;
    ForeignKeys: "contacts_organization_id_fkey";
    Flags: {
      timestamps: true;
      tenant: "organization_id";
    };
  };
  customer_tags: {
    Row: {
      customer_id: string;
      tag_id: string;
      organization_id: string;
    };
    Insert: {
      customer_id: string;
      tag_id: string;
      organization_id: string;
    };
    Update: {
      customer_id?: string;
      tag_id?: string;
      organization_id?: string;
    };
    Relations: {
      customer: { table: "customers"; kind: "one"; nullable: false };
      organization: { table: "organizations"; kind: "one"; nullable: false };
      tag: { table: "tags"; kind: "one"; nullable: false };
    };
    PrimaryKey: "customer_id" | "tag_id";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "customer_tags_customer_id_fkey" | "customer_tags_organization_id_fkey" | "customer_tags_tag_id_fkey";
    Flags: {
      tenant: "organization_id";
    };
  };
  customers: {
    Row: {
      id: string;
      organization_id: string;
      name: string;
      kvk: string | null;
      status: "lead" | "active" | "archived";
      primary_contact_id: string | null;
      metadata: { source?: string; tier?: 'free' | 'pro' };
      created_by: string | null;
      updated_by: string | null;
      archived_at: string | null;
      created_at: string;
      updated_at: string;
      logo_path: StoragePath<"customer-logos"> | null;
    };
    Insert: {
      id?: string;
      organization_id: string;
      name: string;
      kvk?: string | null;
      status?: "lead" | "active" | "archived";
      primary_contact_id?: string | null;
      metadata?: { source?: string; tier?: 'free' | 'pro' };
      created_by?: string | null;
      updated_by?: string | null;
      archived_at?: string | null;
      created_at?: string;
      updated_at?: string;
      logo_path?: StoragePath<"customer-logos"> | null;
    };
    Update: {
      id?: string;
      organization_id?: string;
      name?: string;
      kvk?: string | null;
      status?: "lead" | "active" | "archived";
      primary_contact_id?: string | null;
      metadata?: { source?: string; tier?: 'free' | 'pro' };
      created_by?: string | null;
      updated_by?: string | null;
      archived_at?: string | null;
      created_at?: string;
      updated_at?: string;
      logo_path?: StoragePath<"customer-logos"> | null;
    };
    Relations: {
      customer_tags: { table: "customer_tags"; kind: "many"; nullable: true };
      organization: { table: "organizations"; kind: "one"; nullable: false };
      primary_contact: { table: "contacts"; kind: "one"; nullable: true };
      locations: { table: "locations"; kind: "many"; nullable: true };
      notes: { table: "notes"; kind: "many"; nullable: true };
    };
    PrimaryKey: "id";
    UniqueKeys: {
      customers_id_organization_id_key: readonly ["id", "organization_id"];
      customers_organization_id_kvk_key: readonly ["organization_id", "kvk"];
    };
    Checks: "customers_status_check";
    ForeignKeys: "customers_organization_id_fkey" | "customers_primary_contact_id_fkey";
    Flags: {
      softDelete: "archived_at";
      timestamps: true;
      tenant: "organization_id";
      actor: true;
    };
  };
  locations: {
    Row: {
      id: string;
      organization_id: string;
      customer_id: string;
      label: string;
      city: string | null;
      is_primary: boolean;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      organization_id: string;
      customer_id: string;
      label: string;
      city?: string | null;
      is_primary?: boolean;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      organization_id?: string;
      customer_id?: string;
      label?: string;
      city?: string | null;
      is_primary?: boolean;
      created_at?: string;
      updated_at?: string;
    };
    Relations: {
      customer: { table: "customers"; kind: "one"; nullable: false };
      organization: { table: "organizations"; kind: "one"; nullable: false };
    };
    PrimaryKey: "id";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "locations_customer_id_fkey" | "locations_organization_id_fkey";
    Flags: {
      timestamps: true;
      tenant: "organization_id";
    };
  };
  notes: {
    Row: {
      id: number;
      organization_id: string;
      customer_id: string;
      kind: "call" | "meeting" | "email";
      body: string;
      attachments: Json | null;
      created_at: string;
      updated_at: string;
      embedding: string | null;
    };
    Insert: {
      id?: never;
      organization_id: string;
      customer_id: string;
      kind?: "call" | "meeting" | "email";
      body: string;
      attachments?: Json | null;
      created_at?: string;
      updated_at?: string;
      embedding?: string | null;
    };
    Update: {
      id?: never;
      organization_id?: string;
      customer_id?: string;
      kind?: "call" | "meeting" | "email";
      body?: string;
      attachments?: Json | null;
      created_at?: string;
      updated_at?: string;
      embedding?: string | null;
    };
    Relations: {
      customer: { table: "customers"; kind: "one"; nullable: false };
      organization: { table: "organizations"; kind: "one"; nullable: false };
    };
    PrimaryKey: "id";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "notes_customer_id_fkey" | "notes_organization_id_fkey";
    Flags: {
      timestamps: true;
      tenant: "organization_id";
    };
  };
  notifications: {
    Row: {
      id: number;
      organization_id: string;
      user_id: string;
      title: string;
      read_at: string | null;
      created_at: string;
    };
    Insert: {
      id?: never;
      organization_id: string;
      user_id?: string;
      title: string;
      read_at?: string | null;
      created_at?: string;
    };
    Update: {
      id?: never;
      organization_id?: string;
      user_id?: string;
      title?: string;
      read_at?: string | null;
      created_at?: string;
    };
    Relations: {
      organization: { table: "organizations"; kind: "one"; nullable: false };
    };
    PrimaryKey: "id";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "notifications_organization_id_fkey" | "notifications_user_id_fkey";
    Flags: {
      timestamps: true;
      tenant: "organization_id";
    };
  };
  organizations: {
    Row: {
      id: string;
      name: string;
      slug: string;
      created_at: string;
      updated_at: string;
    };
    Insert: {
      id?: string;
      name: string;
      slug: string;
      created_at?: string;
      updated_at?: string;
    };
    Update: {
      id?: string;
      name?: string;
      slug?: string;
      created_at?: string;
      updated_at?: string;
    };
    Relations: {
      contacts: { table: "contacts"; kind: "many"; nullable: true };
      customer_tags: { table: "customer_tags"; kind: "many"; nullable: true };
      customers: { table: "customers"; kind: "many"; nullable: true };
      locations: { table: "locations"; kind: "many"; nullable: true };
      notes: { table: "notes"; kind: "many"; nullable: true };
      notifications: { table: "notifications"; kind: "many"; nullable: true };
      tags: { table: "tags"; kind: "many"; nullable: true };
    };
    PrimaryKey: "id";
    UniqueKeys: {
      organizations_slug_key: readonly ["slug"];
    };
    Checks: never;
    ForeignKeys: never;
    Flags: {
      timestamps: true;
    };
  };
  tags: {
    Row: {
      id: string;
      organization_id: string;
      name: string;
      color: "gray" | "red" | "green" | "blue";
    };
    Insert: {
      id?: string;
      organization_id: string;
      name: string;
      color?: "gray" | "red" | "green" | "blue";
    };
    Update: {
      id?: string;
      organization_id?: string;
      name?: string;
      color?: "gray" | "red" | "green" | "blue";
    };
    Relations: {
      customer_tags: { table: "customer_tags"; kind: "many"; nullable: true };
      organization: { table: "organizations"; kind: "one"; nullable: false };
    };
    PrimaryKey: "id";
    UniqueKeys: {
      tags_id_organization_id_key: readonly ["id", "organization_id"];
      tags_organization_id_name_key: readonly ["organization_id", "name"];
    };
    Checks: "tags_color_check";
    ForeignKeys: "tags_organization_id_fkey";
    Flags: {
      tenant: "organization_id";
    };
  };
};

export type Functions = {
  rs_workspace_summary: {
    Args: {
      p: Json;
    };
    Returns: Json;
  };
  search_notes: {
    Args: {
      k?: number;
      query: string;
    };
    Returns: (Database["public"]['Tables']["notes"]['Row'])[];
  };
};

export type TableName = keyof Models;
/** Constraint names for `isConflict`, `isCheck` and `isForeignKey`. */
export type UniqueConstraint = { [T in TableName]: Extract<keyof Models[T]['UniqueKeys'], string> }[TableName];
export type CheckConstraint = Models[TableName]['Checks'];
export type ForeignKeyConstraint = Models[TableName]['ForeignKeys'];
export type RowOf<T extends TableName> = Models[T]['Row'];
export type InsertOf<T extends TableName> = Models[T]['Insert'];
export type UpdateOf<T extends TableName> = Models[T]['Update'];

/** Bucket configs for `defineBucket` from `better-supabase/storage`. */
export const buckets = {
  "customerLogos": {
    "id": "customer-logos",
    "public": true,
    "path": "{orgId}/{customerId}/logo/{version}.webp",
    "policy": "tenant",
    "fileSizeLimit": "5MiB",
    "allowedMimeTypes": [
      "image/png",
      "image/jpeg",
      "image/webp"
    ]
  }
} as const;

/** Topic templates for `defineTopic` from `better-supabase/realtime`. */
export const topics = {
  "notifications": "org:{orgId}:notifications:{userId}",
  "customers": "org:{orgId}:customers"
} as const;

export const schema: Schema<Models, Database, Functions> = defineSchema({
  "version": 1,
  "casing": "snake",
  "tables": {
    "contacts": {
      "key": "contacts",
      "name": "contacts",
      "schema": "public",
      "kind": "table",
      "columns": {
        "id": {
          "db": "id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": true
        },
        "organization_id": {
          "db": "organization_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "email": {
          "db": "email",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "full_name": {
          "db": "full_name",
          "type": "text",
          "nullable": true,
          "hasDefault": false
        },
        "created_at": {
          "db": "created_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        },
        "updated_at": {
          "db": "updated_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        }
      },
      "primaryKey": [
        "id"
      ],
      "uniqueKeys": {
        "contacts_id_organization_id_key": [
          "id",
          "organization_id"
        ]
      },
      "relations": {
        "organization": {
          "table": "organizations",
          "kind": "one",
          "nullable": false,
          "foreignKey": "contacts_organization_id_fkey",
          "columns": [
            "organization_id"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        },
        "customers": {
          "table": "customers",
          "kind": "many",
          "nullable": true,
          "foreignKey": "customers_primary_contact_id_fkey",
          "columns": [
            "id",
            "organization_id"
          ],
          "references": [
            "primary_contact_id",
            "organization_id"
          ],
          "direction": "reverse",
          "onDelete": "set null"
        }
      },
      "flags": {
        "timestamps": {
          "createdAt": "created_at",
          "updatedAt": "updated_at"
        },
        "tenant": "organization_id"
      }
    },
    "customer_tags": {
      "key": "customer_tags",
      "name": "customer_tags",
      "schema": "public",
      "kind": "table",
      "columns": {
        "customer_id": {
          "db": "customer_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "tag_id": {
          "db": "tag_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "organization_id": {
          "db": "organization_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        }
      },
      "primaryKey": [
        "customer_id",
        "tag_id"
      ],
      "uniqueKeys": {},
      "relations": {
        "customer": {
          "table": "customers",
          "kind": "one",
          "nullable": false,
          "foreignKey": "customer_tags_customer_id_fkey",
          "columns": [
            "customer_id",
            "organization_id"
          ],
          "references": [
            "id",
            "organization_id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        },
        "organization": {
          "table": "organizations",
          "kind": "one",
          "nullable": false,
          "foreignKey": "customer_tags_organization_id_fkey",
          "columns": [
            "organization_id"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        },
        "tag": {
          "table": "tags",
          "kind": "one",
          "nullable": false,
          "foreignKey": "customer_tags_tag_id_fkey",
          "columns": [
            "tag_id",
            "organization_id"
          ],
          "references": [
            "id",
            "organization_id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        }
      },
      "flags": {
        "tenant": "organization_id"
      }
    },
    "customers": {
      "key": "customers",
      "name": "customers",
      "schema": "public",
      "kind": "table",
      "columns": {
        "id": {
          "db": "id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": true
        },
        "organization_id": {
          "db": "organization_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "name": {
          "db": "name",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "kvk": {
          "db": "kvk",
          "type": "text",
          "nullable": true,
          "hasDefault": false
        },
        "status": {
          "db": "status",
          "type": "text",
          "nullable": false,
          "hasDefault": true,
          "enum": [
            "lead",
            "active",
            "archived"
          ]
        },
        "primary_contact_id": {
          "db": "primary_contact_id",
          "type": "uuid",
          "nullable": true,
          "hasDefault": false
        },
        "metadata": {
          "db": "metadata",
          "type": "jsonb",
          "nullable": false,
          "hasDefault": true,
          "json": true
        },
        "created_by": {
          "db": "created_by",
          "type": "uuid",
          "nullable": true,
          "hasDefault": false
        },
        "updated_by": {
          "db": "updated_by",
          "type": "uuid",
          "nullable": true,
          "hasDefault": false
        },
        "archived_at": {
          "db": "archived_at",
          "type": "timestamptz",
          "nullable": true,
          "hasDefault": false
        },
        "created_at": {
          "db": "created_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        },
        "updated_at": {
          "db": "updated_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        },
        "logo_path": {
          "db": "logo_path",
          "type": "text",
          "nullable": true,
          "hasDefault": false,
          "storage": "customer-logos"
        }
      },
      "primaryKey": [
        "id"
      ],
      "uniqueKeys": {
        "customers_id_organization_id_key": [
          "id",
          "organization_id"
        ],
        "customers_organization_id_kvk_key": [
          "organization_id",
          "kvk"
        ]
      },
      "relations": {
        "customer_tags": {
          "table": "customer_tags",
          "kind": "many",
          "nullable": true,
          "foreignKey": "customer_tags_customer_id_fkey",
          "columns": [
            "id",
            "organization_id"
          ],
          "references": [
            "customer_id",
            "organization_id"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "organization": {
          "table": "organizations",
          "kind": "one",
          "nullable": false,
          "foreignKey": "customers_organization_id_fkey",
          "columns": [
            "organization_id"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        },
        "primary_contact": {
          "table": "contacts",
          "kind": "one",
          "nullable": true,
          "foreignKey": "customers_primary_contact_id_fkey",
          "columns": [
            "primary_contact_id",
            "organization_id"
          ],
          "references": [
            "id",
            "organization_id"
          ],
          "direction": "forward",
          "onDelete": "set null"
        },
        "locations": {
          "table": "locations",
          "kind": "many",
          "nullable": true,
          "foreignKey": "locations_customer_id_fkey",
          "columns": [
            "id",
            "organization_id"
          ],
          "references": [
            "customer_id",
            "organization_id"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "notes": {
          "table": "notes",
          "kind": "many",
          "nullable": true,
          "foreignKey": "notes_customer_id_fkey",
          "columns": [
            "id",
            "organization_id"
          ],
          "references": [
            "customer_id",
            "organization_id"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        }
      },
      "flags": {
        "softDelete": "archived_at",
        "timestamps": {
          "createdAt": "created_at",
          "updatedAt": "updated_at"
        },
        "tenant": "organization_id",
        "actor": {
          "createdBy": "created_by",
          "updatedBy": "updated_by"
        }
      }
    },
    "locations": {
      "key": "locations",
      "name": "locations",
      "schema": "public",
      "kind": "table",
      "columns": {
        "id": {
          "db": "id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": true
        },
        "organization_id": {
          "db": "organization_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "customer_id": {
          "db": "customer_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "label": {
          "db": "label",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "city": {
          "db": "city",
          "type": "text",
          "nullable": true,
          "hasDefault": false
        },
        "is_primary": {
          "db": "is_primary",
          "type": "bool",
          "nullable": false,
          "hasDefault": true
        },
        "created_at": {
          "db": "created_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        },
        "updated_at": {
          "db": "updated_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        }
      },
      "primaryKey": [
        "id"
      ],
      "uniqueKeys": {},
      "relations": {
        "customer": {
          "table": "customers",
          "kind": "one",
          "nullable": false,
          "foreignKey": "locations_customer_id_fkey",
          "columns": [
            "customer_id",
            "organization_id"
          ],
          "references": [
            "id",
            "organization_id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        },
        "organization": {
          "table": "organizations",
          "kind": "one",
          "nullable": false,
          "foreignKey": "locations_organization_id_fkey",
          "columns": [
            "organization_id"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        }
      },
      "flags": {
        "timestamps": {
          "createdAt": "created_at",
          "updatedAt": "updated_at"
        },
        "tenant": "organization_id"
      }
    },
    "notes": {
      "key": "notes",
      "name": "notes",
      "schema": "public",
      "kind": "table",
      "columns": {
        "id": {
          "db": "id",
          "type": "int8",
          "nullable": false,
          "hasDefault": true,
          "generated": true,
          "identity": "always"
        },
        "organization_id": {
          "db": "organization_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "customer_id": {
          "db": "customer_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "kind": {
          "db": "kind",
          "type": "note_kind",
          "nullable": false,
          "hasDefault": true,
          "enum": [
            "call",
            "meeting",
            "email"
          ]
        },
        "body": {
          "db": "body",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "attachments": {
          "db": "attachments",
          "type": "jsonb",
          "nullable": true,
          "hasDefault": false,
          "json": true
        },
        "created_at": {
          "db": "created_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        },
        "updated_at": {
          "db": "updated_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        },
        "embedding": {
          "db": "embedding",
          "type": "vector",
          "nullable": true,
          "hasDefault": false
        }
      },
      "primaryKey": [
        "id"
      ],
      "uniqueKeys": {},
      "relations": {
        "customer": {
          "table": "customers",
          "kind": "one",
          "nullable": false,
          "foreignKey": "notes_customer_id_fkey",
          "columns": [
            "customer_id",
            "organization_id"
          ],
          "references": [
            "id",
            "organization_id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        },
        "organization": {
          "table": "organizations",
          "kind": "one",
          "nullable": false,
          "foreignKey": "notes_organization_id_fkey",
          "columns": [
            "organization_id"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        }
      },
      "flags": {
        "timestamps": {
          "createdAt": "created_at",
          "updatedAt": "updated_at"
        },
        "tenant": "organization_id"
      }
    },
    "notifications": {
      "key": "notifications",
      "name": "notifications",
      "schema": "public",
      "kind": "table",
      "columns": {
        "id": {
          "db": "id",
          "type": "int8",
          "nullable": false,
          "hasDefault": true,
          "generated": true,
          "identity": "always"
        },
        "organization_id": {
          "db": "organization_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "user_id": {
          "db": "user_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": true
        },
        "title": {
          "db": "title",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "read_at": {
          "db": "read_at",
          "type": "timestamptz",
          "nullable": true,
          "hasDefault": false
        },
        "created_at": {
          "db": "created_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        }
      },
      "primaryKey": [
        "id"
      ],
      "uniqueKeys": {},
      "relations": {
        "organization": {
          "table": "organizations",
          "kind": "one",
          "nullable": false,
          "foreignKey": "notifications_organization_id_fkey",
          "columns": [
            "organization_id"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        }
      },
      "flags": {
        "timestamps": {
          "createdAt": "created_at"
        },
        "tenant": "organization_id"
      }
    },
    "organizations": {
      "key": "organizations",
      "name": "organizations",
      "schema": "public",
      "kind": "table",
      "columns": {
        "id": {
          "db": "id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": true
        },
        "name": {
          "db": "name",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "slug": {
          "db": "slug",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "created_at": {
          "db": "created_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        },
        "updated_at": {
          "db": "updated_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        }
      },
      "primaryKey": [
        "id"
      ],
      "uniqueKeys": {
        "organizations_slug_key": [
          "slug"
        ]
      },
      "relations": {
        "contacts": {
          "table": "contacts",
          "kind": "many",
          "nullable": true,
          "foreignKey": "contacts_organization_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "organization_id"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "customer_tags": {
          "table": "customer_tags",
          "kind": "many",
          "nullable": true,
          "foreignKey": "customer_tags_organization_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "organization_id"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "customers": {
          "table": "customers",
          "kind": "many",
          "nullable": true,
          "foreignKey": "customers_organization_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "organization_id"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "locations": {
          "table": "locations",
          "kind": "many",
          "nullable": true,
          "foreignKey": "locations_organization_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "organization_id"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "notes": {
          "table": "notes",
          "kind": "many",
          "nullable": true,
          "foreignKey": "notes_organization_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "organization_id"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "notifications": {
          "table": "notifications",
          "kind": "many",
          "nullable": true,
          "foreignKey": "notifications_organization_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "organization_id"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "tags": {
          "table": "tags",
          "kind": "many",
          "nullable": true,
          "foreignKey": "tags_organization_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "organization_id"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        }
      },
      "flags": {
        "timestamps": {
          "createdAt": "created_at",
          "updatedAt": "updated_at"
        }
      }
    },
    "tags": {
      "key": "tags",
      "name": "tags",
      "schema": "public",
      "kind": "table",
      "columns": {
        "id": {
          "db": "id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": true
        },
        "organization_id": {
          "db": "organization_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "name": {
          "db": "name",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "color": {
          "db": "color",
          "type": "text",
          "nullable": false,
          "hasDefault": true,
          "enum": [
            "gray",
            "red",
            "green",
            "blue"
          ]
        }
      },
      "primaryKey": [
        "id"
      ],
      "uniqueKeys": {
        "tags_id_organization_id_key": [
          "id",
          "organization_id"
        ],
        "tags_organization_id_name_key": [
          "organization_id",
          "name"
        ]
      },
      "relations": {
        "customer_tags": {
          "table": "customer_tags",
          "kind": "many",
          "nullable": true,
          "foreignKey": "customer_tags_tag_id_fkey",
          "columns": [
            "id",
            "organization_id"
          ],
          "references": [
            "tag_id",
            "organization_id"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "organization": {
          "table": "organizations",
          "kind": "one",
          "nullable": false,
          "foreignKey": "tags_organization_id_fkey",
          "columns": [
            "organization_id"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        }
      },
      "flags": {
        "tenant": "organization_id"
      }
    }
  },
  "enums": {
    "note_kind": [
      "call",
      "meeting",
      "email"
    ]
  },
  "functions": {
    "rs_workspace_summary": {
      "name": "rs_workspace_summary",
      "schema": "public",
      "args": [
        {
          "name": "p",
          "type": "jsonb"
        }
      ],
      "returns": "jsonb",
      "returnsSet": false,
      "volatility": "stable"
    },
    "search_notes": {
      "name": "search_notes",
      "schema": "public",
      "args": [
        {
          "name": "k",
          "type": "int4"
        },
        {
          "name": "query",
          "type": "vector"
        }
      ],
      "returns": "notes",
      "returnsSet": true,
      "volatility": "stable"
    }
  },
  "buckets": {
    "customerLogos": {
      "id": "customer-logos",
      "public": true,
      "path": "{orgId}/{customerId}/logo/{version}.webp",
      "policy": "tenant",
      "fileSizeLimit": "5MiB",
      "allowedMimeTypes": [
        "image/png",
        "image/jpeg",
        "image/webp"
      ]
    }
  },
  "topics": {
    "notifications": "org:{orgId}:notifications:{userId}",
    "customers": "org:{orgId}:customers"
  }
});
