import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

import type { ResolvedConfig } from "../../config/index.ts";
import type { AnyCommand, CliArgs } from "../command.ts";
import type { CliEnv } from "../env.ts";
import type { CommandResult } from "../io.ts";

import { isSeed } from "../../testing/index.ts";
import { defineCliCommand } from "../command.ts";
import { databaseUrl, importExport, stdinDatabaseUrl } from "../config.ts";
import { connect } from "../db.ts";
import { display, writeIfChanged } from "../io.ts";
import { withSpinner } from "../prompts.ts";

const ARGS = {
  check: {
    type: "boolean",
    description: "Fail when the SQL file is out of date",
  },
  apply: {
    type: "boolean",
    description:
      "Also insert the rows into the database ($DATABASE_URL, --db-url-stdin, or the local stack)",
  },
  entry: {
    type: "string",
    description: "Defaults to seed.entry (supabase/seed.ts)",
    valueHint: "file",
  },
  out: {
    type: "string",
    description:
      "Defaults to seed.output (supabase/seeds/000_better_supabase.sql)",
    valueHint: "file",
  },
  "db-url-stdin": {
    type: "boolean",
    description:
      "Read the connection string from stdin instead of $DATABASE_URL or the config",
  },
} as const;

export type SeedArgs = CliArgs<typeof ARGS>;

const HEADER = "-- Generated by `better-supabase seed`";

export async function runSeed(
  config: ResolvedConfig,
  args: SeedArgs,
  env: CliEnv,
  open: typeof connect = connect,
  dbUrl?: string,
): Promise<CommandResult> {
  const entry = args.entry ?? config.seed.entry;
  const out = args.out ?? config.seed.output;
  const seed = await importExport(resolve(config.root, entry), "seed");
  if (!isSeed(seed)) {
    return {
      code: 1,
      error: `${display(config.root, entry)} must export defineSeed(...) as \`seed\` or default.`,
    };
  }
  const statements = seed.statements();
  const contents = `${HEADER} from ${display(config.root, entry)}. Do not edit.\n\n${statements.join("\n\n")}\n`;
  const path = resolve(config.root, out);
  const current = existsSync(path) ? await readFile(path, "utf8") : undefined;

  if (args.check === true) {
    return current === contents
      ? { code: 0, output: `${display(config.root, out)} is up to date.` }
      : {
          code: 1,
          error: `${display(config.root, out)} is out of date. Run \`better-supabase seed\`.`,
        };
  }
  if (current !== undefined && !current.startsWith(HEADER)) {
    return {
      code: 1,
      error: `${display(config.root, out)} was not written by better-supabase; pass --out to write elsewhere.`,
    };
  }
  const wrote = await writeIfChanged(path, contents);
  const lines = [
    `${wrote ? "Wrote" : "Unchanged"} ${display(config.root, out)} (${statements.length} table${statements.length === 1 ? "" : "s"})`,
  ];
  if (args.apply === true) {
    const { client, close } = await open(await databaseUrl(config, env, dbUrl));
    try {
      await client.query("begin");
      for (const text of statements) await client.query(text);
      await client.query("commit");
    } catch (error) {
      await client.query("rollback");
      throw error;
    } finally {
      await close();
    }
    lines.push("Inserted the fixtures (existing rows were kept).");
  }
  const toml = resolve(config.root, "supabase/config.toml");
  const seedPath = out.startsWith("supabase/")
    ? `./${out.slice("supabase/".length)}`
    : out;
  if (existsSync(toml)) {
    const text = await readFile(toml, "utf8");
    const folder = seedPath.replace(/[^/]+$/, "");
    if (!text.includes(seedPath) && !text.includes(`${folder}*`)) {
      lines.push(
        "",
        "Add it to supabase/config.toml so `supabase db reset` runs it:",
        "  [db.seed]",
        `  sql_paths = ["./seed.sql", "${seedPath}"]`,
      );
    }
  }
  return { code: 0, output: lines.join("\n") };
}

export const seedCommand: AnyCommand = defineCliCommand({
  meta: {
    name: "seed",
    description:
      "Renders the fixtures from defineSeed() (better-supabase/testing) to SQL",
  },
  args: ARGS,
  run: async (args, { config, env, io }) => {
    const dbUrl = await stdinDatabaseUrl(args["db-url-stdin"], io);
    return withSpinner(
      args.apply === true ? io.prompts : undefined,
      "Inserting the seed rows",
      () => runSeed(config, args, env, connect, dbUrl),
    );
  },
});
