import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

import type { ResolvedConfig } from "../../config/index.ts";
import type { ParsedArgs } from "../args.ts";
import type { CommandResult } from "../io.ts";

import { isSeed } from "../../testing/seed.ts";
import { flagBool, flagString } from "../args.ts";
import { databaseUrl, importExport } from "../config.ts";
import { connect } from "../db.ts";
import { display, writeIfChanged } from "../io.ts";

export const SEED_HELP = `Usage: better-supabase seed [--check] [--apply] [--entry supabase/seed.ts] [--out <file>]

Renders the fixtures from defineSeed() (better-supabase/testing) to SQL.

Options
  --check          Fail when the SQL file is out of date
  --apply          Also insert the rows into the database (--db-url, or the local stack)
  --entry <file>   Defaults to seed.entry (supabase/seed.ts)
  --out <file>     Defaults to seed.output (supabase/seeds/000_better_supabase.sql)`;

const HEADER = "-- Generated by `better-supabase seed`";

export async function runSeed(
  config: ResolvedConfig,
  args: ParsedArgs,
  env: Readonly<Record<string, string | undefined>>,
): Promise<CommandResult> {
  const entry = flagString(args.flags, "entry") ?? config.seed.entry;
  const out = flagString(args.flags, "out") ?? config.seed.output;
  const seed = await importExport(resolve(config.root, entry), "seed");
  if (!isSeed(seed)) {
    return {
      code: 1,
      error: `${display(config.root, entry)} must export defineSeed(...) as \`seed\` or default.`,
    };
  }
  const statements = seed.statements();
  const contents = `${HEADER} from ${display(config.root, entry)}. Do not edit.\n\n${statements.join("\n\n")}\n`;
  const path = resolve(config.root, out);
  const current = existsSync(path) ? await readFile(path, "utf8") : undefined;

  if (flagBool(args.flags, "check")) {
    return current === contents
      ? { code: 0, output: `${display(config.root, out)} is up to date.` }
      : {
          code: 1,
          error: `${display(config.root, out)} is out of date. Run \`better-supabase seed\`.`,
        };
  }
  if (current !== undefined && !current.startsWith(HEADER)) {
    return {
      code: 1,
      error: `${display(config.root, out)} was not written by better-supabase; pass --out to write elsewhere.`,
    };
  }
  const wrote = await writeIfChanged(path, contents);
  const lines = [
    `${wrote ? "Wrote" : "Unchanged"} ${display(config.root, out)} (${statements.length} table${statements.length === 1 ? "" : "s"})`,
  ];
  if (flagBool(args.flags, "apply")) {
    const { client, close } = await connect(
      await databaseUrl(config, env, flagString(args.flags, "db-url")),
    );
    try {
      await client.query("begin");
      for (const text of statements) await client.query(text);
      await client.query("commit");
    } catch (error) {
      await client.query("rollback");
      throw error;
    } finally {
      await close();
    }
    lines.push("Inserted the fixtures (existing rows were kept).");
  }
  const toml = resolve(config.root, "supabase/config.toml");
  const seedPath = out.startsWith("supabase/")
    ? `./${out.slice("supabase/".length)}`
    : out;
  if (existsSync(toml)) {
    const text = await readFile(toml, "utf8");
    const folder = seedPath.replace(/[^/]+$/, "");
    if (!text.includes(seedPath) && !text.includes(`${folder}*`)) {
      lines.push(
        "",
        "Add it to supabase/config.toml so `supabase db reset` runs it:",
        "  [db.seed]",
        `  sql_paths = ["./seed.sql", "${seedPath}"]`,
      );
    }
  }
  return { code: 0, output: lines.join("\n") };
}
