-- Generated by pg-delta when the fixture switched to it. migra never emits the
-- Postgres 17 MAINTAIN privilege, so the default privileges left it on
-- notifications for anon and authenticated; these statements remove it.
REVOKE ALL ON TABLE "public"."notifications" FROM "anon";

REVOKE ALL ON TABLE "public"."notifications" FROM "authenticated";

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."notifications" TO "authenticated";
