// @generated by better-supabase gen. Do not edit; run `better-supabase gen` instead.
/* oxlint-disable */
/* eslint-disable */

import { defineSchema, type Schema } from "better-supabase";
import type { EnrichDatabase } from "better-supabase";
import type { Database as SupabaseDatabase } from "./database.types.ts";

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = EnrichDatabase<
  SupabaseDatabase,
  {
    public: {
      customers: {
        status: "lead" | "active" | "archived";
      };
      tags: {
        color: "gray" | "red" | "green" | "blue";
      };
    };
  }
>;

export const noteKindValues = ["call", "meeting", "email"] as const;
export type NoteKind = (typeof noteKindValues)[number];
export const customersStatusValues = ["lead", "active", "archived"] as const;
export type CustomersStatus = (typeof customersStatusValues)[number];
export const tagsColorValues = ["gray", "red", "green", "blue"] as const;
export type TagsColor = (typeof tagsColorValues)[number];

export type Models = {
  contacts: {
    Row: {
      id: string;
      organizationId: string;
      email: string;
      fullName: string | null;
      createdAt: string;
      updatedAt: string;
    };
    Insert: {
      id?: string;
      organizationId: string;
      email: string;
      fullName?: string | null;
      createdAt?: string;
      updatedAt?: string;
    };
    Update: {
      id?: string;
      organizationId?: string;
      email?: string;
      fullName?: string | null;
      createdAt?: string;
      updatedAt?: string;
    };
    Relations: {
      organization: { table: "organizations"; kind: "one"; nullable: false };
      customers: { table: "customers"; kind: "many"; nullable: true };
    };
    PrimaryKey: "id";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "contacts_organization_id_fkey";
    Flags: Record<never, never>;
  };
  customerTags: {
    Row: {
      customerId: string;
      tagId: string;
      organizationId: string;
    };
    Insert: {
      customerId: string;
      tagId: string;
      organizationId: string;
    };
    Update: {
      customerId?: string;
      tagId?: string;
      organizationId?: string;
    };
    Relations: {
      customer: { table: "customers"; kind: "one"; nullable: false };
      organization: { table: "organizations"; kind: "one"; nullable: false };
      tag: { table: "tags"; kind: "one"; nullable: false };
    };
    PrimaryKey: "customerId" | "tagId";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "customer_tags_customer_id_fkey" | "customer_tags_organization_id_fkey" | "customer_tags_tag_id_fkey";
    Flags: Record<never, never>;
  };
  customers: {
    Row: {
      id: string;
      organizationId: string;
      name: string;
      kvk: string | null;
      status: "lead" | "active" | "archived";
      primaryContactId: string | null;
      metadata: Json;
      createdBy: string | null;
      updatedBy: string | null;
      archivedAt: string | null;
      createdAt: string;
      updatedAt: string;
      logoPath: string | null;
    };
    Insert: {
      id?: string;
      organizationId: string;
      name: string;
      kvk?: string | null;
      status?: "lead" | "active" | "archived";
      primaryContactId?: string | null;
      metadata?: Json;
      createdBy?: string | null;
      updatedBy?: string | null;
      archivedAt?: string | null;
      createdAt?: string;
      updatedAt?: string;
      logoPath?: string | null;
    };
    Update: {
      id?: string;
      organizationId?: string;
      name?: string;
      kvk?: string | null;
      status?: "lead" | "active" | "archived";
      primaryContactId?: string | null;
      metadata?: Json;
      createdBy?: string | null;
      updatedBy?: string | null;
      archivedAt?: string | null;
      createdAt?: string;
      updatedAt?: string;
      logoPath?: string | null;
    };
    Relations: {
      customerTags: { table: "customerTags"; kind: "many"; nullable: true };
      organization: { table: "organizations"; kind: "one"; nullable: false };
      primaryContact: { table: "contacts"; kind: "one"; nullable: true };
      locations: { table: "locations"; kind: "many"; nullable: true };
      notes: { table: "notes"; kind: "many"; nullable: true };
    };
    PrimaryKey: "id";
    UniqueKeys: {
      customers_organization_id_kvk_key: readonly ["organizationId", "kvk"];
    };
    Checks: "customers_status_check";
    ForeignKeys: "customers_organization_id_fkey" | "customers_primary_contact_id_fkey";
    Flags: Record<never, never>;
  };
  locations: {
    Row: {
      id: string;
      organizationId: string;
      customerId: string;
      label: string;
      city: string | null;
      isPrimary: boolean;
      createdAt: string;
      updatedAt: string;
    };
    Insert: {
      id?: string;
      organizationId: string;
      customerId: string;
      label: string;
      city?: string | null;
      isPrimary?: boolean;
      createdAt?: string;
      updatedAt?: string;
    };
    Update: {
      id?: string;
      organizationId?: string;
      customerId?: string;
      label?: string;
      city?: string | null;
      isPrimary?: boolean;
      createdAt?: string;
      updatedAt?: string;
    };
    Relations: {
      customer: { table: "customers"; kind: "one"; nullable: false };
      organization: { table: "organizations"; kind: "one"; nullable: false };
    };
    PrimaryKey: "id";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "locations_customer_id_fkey" | "locations_organization_id_fkey";
    Flags: Record<never, never>;
  };
  notes: {
    Row: {
      id: number;
      organizationId: string;
      customerId: string;
      kind: "call" | "meeting" | "email";
      body: string;
      attachments: Json | null;
      createdAt: string;
      updatedAt: string;
      embedding: string | null;
    };
    Insert: {
      id?: never;
      organizationId: string;
      customerId: string;
      kind?: "call" | "meeting" | "email";
      body: string;
      attachments?: Json | null;
      createdAt?: string;
      updatedAt?: string;
      embedding?: string | null;
    };
    Update: {
      id?: never;
      organizationId?: string;
      customerId?: string;
      kind?: "call" | "meeting" | "email";
      body?: string;
      attachments?: Json | null;
      createdAt?: string;
      updatedAt?: string;
      embedding?: string | null;
    };
    Relations: {
      customer: { table: "customers"; kind: "one"; nullable: false };
      organization: { table: "organizations"; kind: "one"; nullable: false };
    };
    PrimaryKey: "id";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "notes_customer_id_fkey" | "notes_organization_id_fkey";
    Flags: Record<never, never>;
  };
  notifications: {
    Row: {
      id: number;
      organizationId: string;
      userId: string;
      title: string;
      readAt: string | null;
      createdAt: string;
    };
    Insert: {
      id?: never;
      organizationId: string;
      userId?: string;
      title: string;
      readAt?: string | null;
      createdAt?: string;
    };
    Update: {
      id?: never;
      organizationId?: string;
      userId?: string;
      title?: string;
      readAt?: string | null;
      createdAt?: string;
    };
    Relations: {
      organization: { table: "organizations"; kind: "one"; nullable: false };
    };
    PrimaryKey: "id";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "notifications_organization_id_fkey" | "notifications_user_id_fkey";
    Flags: Record<never, never>;
  };
  organizations: {
    Row: {
      id: string;
      name: string;
      slug: string;
      createdAt: string;
      updatedAt: string;
    };
    Insert: {
      id?: string;
      name: string;
      slug: string;
      createdAt?: string;
      updatedAt?: string;
    };
    Update: {
      id?: string;
      name?: string;
      slug?: string;
      createdAt?: string;
      updatedAt?: string;
    };
    Relations: {
      contacts: { table: "contacts"; kind: "many"; nullable: true };
      customerTags: { table: "customerTags"; kind: "many"; nullable: true };
      customers: { table: "customers"; kind: "many"; nullable: true };
      locations: { table: "locations"; kind: "many"; nullable: true };
      notes: { table: "notes"; kind: "many"; nullable: true };
      notifications: { table: "notifications"; kind: "many"; nullable: true };
      tags: { table: "tags"; kind: "many"; nullable: true };
    };
    PrimaryKey: "id";
    UniqueKeys: {
      organizations_slug_key: readonly ["slug"];
    };
    Checks: never;
    ForeignKeys: never;
    Flags: Record<never, never>;
  };
  tags: {
    Row: {
      id: string;
      organizationId: string;
      name: string;
      color: "gray" | "red" | "green" | "blue";
    };
    Insert: {
      id?: string;
      organizationId: string;
      name: string;
      color?: "gray" | "red" | "green" | "blue";
    };
    Update: {
      id?: string;
      organizationId?: string;
      name?: string;
      color?: "gray" | "red" | "green" | "blue";
    };
    Relations: {
      customerTags: { table: "customerTags"; kind: "many"; nullable: true };
      organization: { table: "organizations"; kind: "one"; nullable: false };
    };
    PrimaryKey: "id";
    UniqueKeys: {
      tags_organization_id_name_key: readonly ["organizationId", "name"];
    };
    Checks: "tags_color_check";
    ForeignKeys: "tags_organization_id_fkey";
    Flags: Record<never, never>;
  };
};

export type Functions = {
  rs_workspace_summary: {
    Args: {
      p: Json;
    };
    Returns: Json;
  };
  search_notes: {
    Args: {
      k?: number;
      query: string;
    };
    Returns: (Database["public"]['Tables']["notes"]['Row'])[];
  };
};

export type TableName = keyof Models;
/** Constraint names for `isConflict`, `isCheck` and `isForeignKey`. */
export type UniqueConstraint = { [T in TableName]: Extract<keyof Models[T]['UniqueKeys'], string> }[TableName];
export type CheckConstraint = Models[TableName]['Checks'];
export type ForeignKeyConstraint = Models[TableName]['ForeignKeys'];
export type RowOf<T extends TableName> = Models[T]['Row'];
export type InsertOf<T extends TableName> = Models[T]['Insert'];
export type UpdateOf<T extends TableName> = Models[T]['Update'];

export const schema: Schema<Models, Database, Functions> = defineSchema({
  "version": 1,
  "casing": "camel",
  "tables": {
    "contacts": {
      "key": "contacts",
      "name": "contacts",
      "schema": "public",
      "kind": "table",
      "columns": {
        "id": {
          "db": "id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": true
        },
        "organizationId": {
          "db": "organization_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "email": {
          "db": "email",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "fullName": {
          "db": "full_name",
          "type": "text",
          "nullable": true,
          "hasDefault": false
        },
        "createdAt": {
          "db": "created_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        },
        "updatedAt": {
          "db": "updated_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        }
      },
      "primaryKey": [
        "id"
      ],
      "uniqueKeys": {},
      "relations": {
        "organization": {
          "table": "organizations",
          "kind": "one",
          "nullable": false,
          "foreignKey": "contacts_organization_id_fkey",
          "columns": [
            "organizationId"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        },
        "customers": {
          "table": "customers",
          "kind": "many",
          "nullable": true,
          "foreignKey": "customers_primary_contact_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "primaryContactId"
          ],
          "direction": "reverse",
          "onDelete": "set null"
        }
      },
      "flags": {}
    },
    "customerTags": {
      "key": "customerTags",
      "name": "customer_tags",
      "schema": "public",
      "kind": "table",
      "columns": {
        "customerId": {
          "db": "customer_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "tagId": {
          "db": "tag_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "organizationId": {
          "db": "organization_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        }
      },
      "primaryKey": [
        "customerId",
        "tagId"
      ],
      "uniqueKeys": {},
      "relations": {
        "customer": {
          "table": "customers",
          "kind": "one",
          "nullable": false,
          "foreignKey": "customer_tags_customer_id_fkey",
          "columns": [
            "customerId"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        },
        "organization": {
          "table": "organizations",
          "kind": "one",
          "nullable": false,
          "foreignKey": "customer_tags_organization_id_fkey",
          "columns": [
            "organizationId"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        },
        "tag": {
          "table": "tags",
          "kind": "one",
          "nullable": false,
          "foreignKey": "customer_tags_tag_id_fkey",
          "columns": [
            "tagId"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        }
      },
      "flags": {}
    },
    "customers": {
      "key": "customers",
      "name": "customers",
      "schema": "public",
      "kind": "table",
      "columns": {
        "id": {
          "db": "id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": true
        },
        "organizationId": {
          "db": "organization_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "name": {
          "db": "name",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "kvk": {
          "db": "kvk",
          "type": "text",
          "nullable": true,
          "hasDefault": false
        },
        "status": {
          "db": "status",
          "type": "text",
          "nullable": false,
          "hasDefault": true,
          "enum": [
            "lead",
            "active",
            "archived"
          ]
        },
        "primaryContactId": {
          "db": "primary_contact_id",
          "type": "uuid",
          "nullable": true,
          "hasDefault": false
        },
        "metadata": {
          "db": "metadata",
          "type": "jsonb",
          "nullable": false,
          "hasDefault": true,
          "json": true
        },
        "createdBy": {
          "db": "created_by",
          "type": "uuid",
          "nullable": true,
          "hasDefault": false
        },
        "updatedBy": {
          "db": "updated_by",
          "type": "uuid",
          "nullable": true,
          "hasDefault": false
        },
        "archivedAt": {
          "db": "archived_at",
          "type": "timestamptz",
          "nullable": true,
          "hasDefault": false
        },
        "createdAt": {
          "db": "created_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        },
        "updatedAt": {
          "db": "updated_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        },
        "logoPath": {
          "db": "logo_path",
          "type": "text",
          "nullable": true,
          "hasDefault": false
        }
      },
      "primaryKey": [
        "id"
      ],
      "uniqueKeys": {
        "customers_organization_id_kvk_key": [
          "organizationId",
          "kvk"
        ]
      },
      "relations": {
        "customerTags": {
          "table": "customerTags",
          "kind": "many",
          "nullable": true,
          "foreignKey": "customer_tags_customer_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "customerId"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "organization": {
          "table": "organizations",
          "kind": "one",
          "nullable": false,
          "foreignKey": "customers_organization_id_fkey",
          "columns": [
            "organizationId"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        },
        "primaryContact": {
          "table": "contacts",
          "kind": "one",
          "nullable": true,
          "foreignKey": "customers_primary_contact_id_fkey",
          "columns": [
            "primaryContactId"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "set null"
        },
        "locations": {
          "table": "locations",
          "kind": "many",
          "nullable": true,
          "foreignKey": "locations_customer_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "customerId"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "notes": {
          "table": "notes",
          "kind": "many",
          "nullable": true,
          "foreignKey": "notes_customer_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "customerId"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        }
      },
      "flags": {}
    },
    "locations": {
      "key": "locations",
      "name": "locations",
      "schema": "public",
      "kind": "table",
      "columns": {
        "id": {
          "db": "id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": true
        },
        "organizationId": {
          "db": "organization_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "customerId": {
          "db": "customer_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "label": {
          "db": "label",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "city": {
          "db": "city",
          "type": "text",
          "nullable": true,
          "hasDefault": false
        },
        "isPrimary": {
          "db": "is_primary",
          "type": "bool",
          "nullable": false,
          "hasDefault": true
        },
        "createdAt": {
          "db": "created_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        },
        "updatedAt": {
          "db": "updated_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        }
      },
      "primaryKey": [
        "id"
      ],
      "uniqueKeys": {},
      "relations": {
        "customer": {
          "table": "customers",
          "kind": "one",
          "nullable": false,
          "foreignKey": "locations_customer_id_fkey",
          "columns": [
            "customerId"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        },
        "organization": {
          "table": "organizations",
          "kind": "one",
          "nullable": false,
          "foreignKey": "locations_organization_id_fkey",
          "columns": [
            "organizationId"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        }
      },
      "flags": {}
    },
    "notes": {
      "key": "notes",
      "name": "notes",
      "schema": "public",
      "kind": "table",
      "columns": {
        "id": {
          "db": "id",
          "type": "int8",
          "nullable": false,
          "hasDefault": true,
          "generated": true,
          "identity": "always"
        },
        "organizationId": {
          "db": "organization_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "customerId": {
          "db": "customer_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "kind": {
          "db": "kind",
          "type": "note_kind",
          "nullable": false,
          "hasDefault": true,
          "enum": [
            "call",
            "meeting",
            "email"
          ]
        },
        "body": {
          "db": "body",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "attachments": {
          "db": "attachments",
          "type": "jsonb",
          "nullable": true,
          "hasDefault": false,
          "json": true
        },
        "createdAt": {
          "db": "created_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        },
        "updatedAt": {
          "db": "updated_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        },
        "embedding": {
          "db": "embedding",
          "type": "vector",
          "nullable": true,
          "hasDefault": false
        }
      },
      "primaryKey": [
        "id"
      ],
      "uniqueKeys": {},
      "relations": {
        "customer": {
          "table": "customers",
          "kind": "one",
          "nullable": false,
          "foreignKey": "notes_customer_id_fkey",
          "columns": [
            "customerId"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        },
        "organization": {
          "table": "organizations",
          "kind": "one",
          "nullable": false,
          "foreignKey": "notes_organization_id_fkey",
          "columns": [
            "organizationId"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        }
      },
      "flags": {}
    },
    "notifications": {
      "key": "notifications",
      "name": "notifications",
      "schema": "public",
      "kind": "table",
      "columns": {
        "id": {
          "db": "id",
          "type": "int8",
          "nullable": false,
          "hasDefault": true,
          "generated": true,
          "identity": "always"
        },
        "organizationId": {
          "db": "organization_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "userId": {
          "db": "user_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": true
        },
        "title": {
          "db": "title",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "readAt": {
          "db": "read_at",
          "type": "timestamptz",
          "nullable": true,
          "hasDefault": false
        },
        "createdAt": {
          "db": "created_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        }
      },
      "primaryKey": [
        "id"
      ],
      "uniqueKeys": {},
      "relations": {
        "organization": {
          "table": "organizations",
          "kind": "one",
          "nullable": false,
          "foreignKey": "notifications_organization_id_fkey",
          "columns": [
            "organizationId"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        }
      },
      "flags": {}
    },
    "organizations": {
      "key": "organizations",
      "name": "organizations",
      "schema": "public",
      "kind": "table",
      "columns": {
        "id": {
          "db": "id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": true
        },
        "name": {
          "db": "name",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "slug": {
          "db": "slug",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "createdAt": {
          "db": "created_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        },
        "updatedAt": {
          "db": "updated_at",
          "type": "timestamptz",
          "nullable": false,
          "hasDefault": true
        }
      },
      "primaryKey": [
        "id"
      ],
      "uniqueKeys": {
        "organizations_slug_key": [
          "slug"
        ]
      },
      "relations": {
        "contacts": {
          "table": "contacts",
          "kind": "many",
          "nullable": true,
          "foreignKey": "contacts_organization_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "organizationId"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "customerTags": {
          "table": "customerTags",
          "kind": "many",
          "nullable": true,
          "foreignKey": "customer_tags_organization_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "organizationId"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "customers": {
          "table": "customers",
          "kind": "many",
          "nullable": true,
          "foreignKey": "customers_organization_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "organizationId"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "locations": {
          "table": "locations",
          "kind": "many",
          "nullable": true,
          "foreignKey": "locations_organization_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "organizationId"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "notes": {
          "table": "notes",
          "kind": "many",
          "nullable": true,
          "foreignKey": "notes_organization_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "organizationId"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "notifications": {
          "table": "notifications",
          "kind": "many",
          "nullable": true,
          "foreignKey": "notifications_organization_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "organizationId"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "tags": {
          "table": "tags",
          "kind": "many",
          "nullable": true,
          "foreignKey": "tags_organization_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "organizationId"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        }
      },
      "flags": {}
    },
    "tags": {
      "key": "tags",
      "name": "tags",
      "schema": "public",
      "kind": "table",
      "columns": {
        "id": {
          "db": "id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": true
        },
        "organizationId": {
          "db": "organization_id",
          "type": "uuid",
          "nullable": false,
          "hasDefault": false
        },
        "name": {
          "db": "name",
          "type": "text",
          "nullable": false,
          "hasDefault": false
        },
        "color": {
          "db": "color",
          "type": "text",
          "nullable": false,
          "hasDefault": true,
          "enum": [
            "gray",
            "red",
            "green",
            "blue"
          ]
        }
      },
      "primaryKey": [
        "id"
      ],
      "uniqueKeys": {
        "tags_organization_id_name_key": [
          "organizationId",
          "name"
        ]
      },
      "relations": {
        "customerTags": {
          "table": "customerTags",
          "kind": "many",
          "nullable": true,
          "foreignKey": "customer_tags_tag_id_fkey",
          "columns": [
            "id"
          ],
          "references": [
            "tagId"
          ],
          "direction": "reverse",
          "onDelete": "cascade"
        },
        "organization": {
          "table": "organizations",
          "kind": "one",
          "nullable": false,
          "foreignKey": "tags_organization_id_fkey",
          "columns": [
            "organizationId"
          ],
          "references": [
            "id"
          ],
          "direction": "forward",
          "onDelete": "cascade"
        }
      },
      "flags": {}
    }
  },
  "enums": {
    "note_kind": [
      "call",
      "meeting",
      "email"
    ]
  },
  "functions": {
    "rs_workspace_summary": {
      "name": "rs_workspace_summary",
      "schema": "public",
      "args": [
        {
          "name": "p",
          "type": "jsonb"
        }
      ],
      "returns": "jsonb",
      "returnsSet": false,
      "volatility": "stable"
    },
    "search_notes": {
      "name": "search_notes",
      "schema": "public",
      "args": [
        {
          "name": "k",
          "type": "int4"
        },
        {
          "name": "query",
          "type": "vector"
        }
      ],
      "returns": "notes",
      "returnsSet": true,
      "volatility": "stable"
    }
  }
});
