// @generated by better-supabase gen. Do not edit; run `better-supabase gen` instead.
/* oxlint-disable */
/* eslint-disable */

import { defineSchema, type Schema } from "better-supabase";
import type { EnrichDatabase, MutableWhere, OrderByArg, OrderByInput } from "better-supabase";
import type { Database as SupabaseDatabase } from "./database.types.ts";
import meta from "./generated.meta.js";

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = EnrichDatabase<
  SupabaseDatabase,
  {
    public: {
      customers: {
        status: "lead" | "active" | "archived";
      };
      tags: {
        color: "gray" | "red" | "green" | "blue";
      };
    };
  }
>;

export const noteKindValues = ["call", "meeting", "email"] as const;
export type NoteKind = (typeof noteKindValues)[number];
export const customersStatusValues = ["lead", "active", "archived"] as const;
export type CustomersStatus = (typeof customersStatusValues)[number];
export const tagsColorValues = ["gray", "red", "green", "blue"] as const;
export type TagsColor = (typeof tagsColorValues)[number];

export type Models = {
  contacts: {
    Row: {
      id: string;
      organizationId: string;
      email: string;
      fullName: string | null;
      createdAt: string;
      updatedAt: string;
    };
    Insert: {
      id?: string;
      organizationId: string;
      email: string;
      fullName?: string | null;
      createdAt?: string;
      updatedAt?: string;
    };
    Update: {
      id?: string;
      organizationId?: string;
      email?: string;
      fullName?: string | null;
      createdAt?: string;
      updatedAt?: string;
    };
    Relations: {
      organization: { table: "organizations"; kind: "one"; nullable: false };
      customers: { table: "customers"; kind: "many"; nullable: true };
    };
    PrimaryKey: "id";
    UniqueKeys: {
      contacts_id_organization_id_key: readonly ["id", "organizationId"];
    };
    Checks: never;
    ForeignKeys: "contacts_organization_id_fkey";
    Flags: Record<never, never>;
  };
  customerTags: {
    Row: {
      customerId: string;
      tagId: string;
      organizationId: string;
      createdAt: string;
    };
    Insert: {
      customerId: string;
      tagId: string;
      organizationId: string;
      createdAt?: string;
    };
    Update: {
      customerId?: string;
      tagId?: string;
      organizationId?: string;
      createdAt?: string;
    };
    Relations: {
      customer: { table: "customers"; kind: "one"; nullable: false };
      organization: { table: "organizations"; kind: "one"; nullable: false };
      tag: { table: "tags"; kind: "one"; nullable: false };
    };
    PrimaryKey: "customerId" | "tagId";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "customer_tags_customer_id_fkey" | "customer_tags_organization_id_fkey" | "customer_tags_tag_id_fkey";
    Flags: Record<never, never>;
  };
  customers: {
    Row: {
      id: string;
      organizationId: string;
      name: string;
      kvk: string | null;
      status: "lead" | "active" | "archived";
      primaryContactId: string | null;
      metadata: Json;
      createdBy: string | null;
      updatedBy: string | null;
      archivedAt: string | null;
      createdAt: string;
      updatedAt: string;
      logoPath: string | null;
    };
    Insert: {
      id?: string;
      organizationId: string;
      name: string;
      kvk?: string | null;
      status?: "lead" | "active" | "archived";
      primaryContactId?: string | null;
      metadata?: Json;
      createdBy?: string | null;
      updatedBy?: string | null;
      archivedAt?: string | null;
      createdAt?: string;
      updatedAt?: string;
      logoPath?: string | null;
    };
    Update: {
      id?: string;
      organizationId?: string;
      name?: string;
      kvk?: string | null;
      status?: "lead" | "active" | "archived";
      primaryContactId?: string | null;
      metadata?: Json;
      createdBy?: string | null;
      updatedBy?: string | null;
      archivedAt?: string | null;
      createdAt?: string;
      updatedAt?: string;
      logoPath?: string | null;
    };
    Relations: {
      customerTags: { table: "customerTags"; kind: "many"; nullable: true };
      organization: { table: "organizations"; kind: "one"; nullable: false };
      primaryContact: { table: "contacts"; kind: "one"; nullable: true };
      locations: { table: "locations"; kind: "many"; nullable: true };
      notes: { table: "notes"; kind: "many"; nullable: true };
    };
    PrimaryKey: "id";
    UniqueKeys: {
      customers_id_organization_id_key: readonly ["id", "organizationId"];
      customers_organization_id_kvk_key: readonly ["organizationId", "kvk"];
    };
    Checks: "customers_name_check" | "customers_status_check";
    ForeignKeys: "customers_organization_id_fkey" | "customers_primary_contact_id_fkey";
    Flags: Record<never, never>;
  };
  locations: {
    Row: {
      id: string;
      organizationId: string;
      customerId: string;
      label: string;
      city: string | null;
      isPrimary: boolean;
      createdAt: string;
      updatedAt: string;
    };
    Insert: {
      id?: string;
      organizationId: string;
      customerId: string;
      label: string;
      city?: string | null;
      isPrimary?: boolean;
      createdAt?: string;
      updatedAt?: string;
    };
    Update: {
      id?: string;
      organizationId?: string;
      customerId?: string;
      label?: string;
      city?: string | null;
      isPrimary?: boolean;
      createdAt?: string;
      updatedAt?: string;
    };
    Relations: {
      customer: { table: "customers"; kind: "one"; nullable: false };
      organization: { table: "organizations"; kind: "one"; nullable: false };
    };
    PrimaryKey: "id";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "locations_customer_id_fkey" | "locations_organization_id_fkey";
    Flags: Record<never, never>;
  };
  notes: {
    Row: {
      id: number;
      organizationId: string;
      customerId: string;
      kind: "call" | "meeting" | "email";
      body: string;
      attachments: Json | null;
      createdAt: string;
      updatedAt: string;
      embedding: string | null;
    };
    Insert: {
      id?: never;
      organizationId: string;
      customerId: string;
      kind?: "call" | "meeting" | "email";
      body: string;
      attachments?: Json | null;
      createdAt?: string;
      updatedAt?: string;
      embedding?: string | null;
    };
    Update: {
      id?: never;
      organizationId?: string;
      customerId?: string;
      kind?: "call" | "meeting" | "email";
      body?: string;
      attachments?: Json | null;
      createdAt?: string;
      updatedAt?: string;
      embedding?: string | null;
    };
    Relations: {
      customer: { table: "customers"; kind: "one"; nullable: false };
      organization: { table: "organizations"; kind: "one"; nullable: false };
    };
    PrimaryKey: "id";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "notes_customer_id_fkey" | "notes_organization_id_fkey";
    Flags: Record<never, never>;
  };
  notifications: {
    Row: {
      id: number;
      organizationId: string;
      userId: string;
      title: string;
      readAt: string | null;
      createdAt: string;
      updatedAt: string;
    };
    Insert: {
      id?: never;
      organizationId: string;
      userId?: string;
      title: string;
      readAt?: string | null;
      createdAt?: string;
      updatedAt?: string;
    };
    Update: {
      id?: never;
      organizationId?: string;
      userId?: string;
      title?: string;
      readAt?: string | null;
      createdAt?: string;
      updatedAt?: string;
    };
    Relations: {
      organization: { table: "organizations"; kind: "one"; nullable: false };
    };
    PrimaryKey: "id";
    UniqueKeys: Record<never, never>;
    Checks: never;
    ForeignKeys: "notifications_organization_id_fkey" | "notifications_user_id_fkey";
    Flags: Record<never, never>;
  };
  organizations: {
    Row: {
      id: string;
      name: string;
      slug: string;
      createdAt: string;
      updatedAt: string;
    };
    Insert: {
      id?: string;
      name: string;
      slug: string;
      createdAt?: string;
      updatedAt?: string;
    };
    Update: {
      id?: string;
      name?: string;
      slug?: string;
      createdAt?: string;
      updatedAt?: string;
    };
    Relations: {
      contacts: { table: "contacts"; kind: "many"; nullable: true };
      customerTags: { table: "customerTags"; kind: "many"; nullable: true };
      customers: { table: "customers"; kind: "many"; nullable: true };
      locations: { table: "locations"; kind: "many"; nullable: true };
      notes: { table: "notes"; kind: "many"; nullable: true };
      notifications: { table: "notifications"; kind: "many"; nullable: true };
      tags: { table: "tags"; kind: "many"; nullable: true };
    };
    PrimaryKey: "id";
    UniqueKeys: {
      organizations_slug_key: readonly ["slug"];
    };
    Checks: never;
    ForeignKeys: never;
    Flags: Record<never, never>;
  };
  tags: {
    Row: {
      id: string;
      organizationId: string;
      name: string;
      color: "gray" | "red" | "green" | "blue";
      createdAt: string;
      updatedAt: string;
    };
    Insert: {
      id?: string;
      organizationId: string;
      name: string;
      color?: "gray" | "red" | "green" | "blue";
      createdAt?: string;
      updatedAt?: string;
    };
    Update: {
      id?: string;
      organizationId?: string;
      name?: string;
      color?: "gray" | "red" | "green" | "blue";
      createdAt?: string;
      updatedAt?: string;
    };
    Relations: {
      customerTags: { table: "customerTags"; kind: "many"; nullable: true };
      organization: { table: "organizations"; kind: "one"; nullable: false };
    };
    PrimaryKey: "id";
    UniqueKeys: {
      tags_id_organization_id_key: readonly ["id", "organizationId"];
      tags_organization_id_name_key: readonly ["organizationId", "name"];
    };
    Checks: "tags_color_check";
    ForeignKeys: "tags_organization_id_fkey";
    Flags: Record<never, never>;
  };
};

export type Functions = {
  customer_note_counts: {
    Args: {
      p_customer_ids?: string[] | null;
    };
    Returns: { "customerId": string | null; "lastNoteAt": string | null; "noteCount": number | null }[];
  };
  customers_by_status: {
    Args: {
      p_limit?: number | null;
      p_status: string | null;
    };
    Returns: (Models["customers"]['Row'])[];
  };
  rs_workspace_summary: {
    Args: {
      p: Json | null;
    };
    Returns: Json;
  };
  search_notes: {
    Args: {
      k?: number | null;
      query: string | null;
    };
    Returns: (Models["notes"]['Row'])[];
  };
  search_notes_scores: {
    Args: {
      k?: number | null;
      query: string | null;
    };
    Returns: { "id": Json; "score": number | null }[];
  };
};

export type TableName = keyof Models;
/** Constraint names for `isConflict`, `isCheck` and `isForeignKey`. */
export type UniqueConstraint = { [T in TableName]: Extract<keyof Models[T]['UniqueKeys'], string> }[TableName];
export type CheckConstraint = Models[TableName]['Checks'];
export type ForeignKeyConstraint = Models[TableName]['ForeignKeys'];
export type RowOf<T extends TableName> = Models[T]['Row'];
export type InsertOf<T extends TableName> = Models[T]['Insert'];
export type UpdateOf<T extends TableName> = Models[T]['Update'];
/** A `where` for `T` you can assign to one key at a time. */
export type WhereOf<T extends TableName> = MutableWhere<Models, T>;
/** An `orderBy` for `T`: one sort or a list, by column or to-one relation. */
export type OrderByOf<T extends TableName> = OrderByArg<Models, T>;
/** One sort term of `T`'s `orderBy`, by column or to-one relation. */
export type OrderTermOf<T extends TableName> = OrderByInput<Models, T>;

export const schema: Schema<Models, Database, Functions> = defineSchema(meta);
